INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('administrador','administrador');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Jefe de UIB','Jefe de UIB');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Ingeniero UIB','Ingeniero UIB');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Secretaria UIB','Secretaria UIB');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Ingeniero residente Tumimed','Ingeniero residente Tumimed');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Técnico Tumimed','Técnico Tumimed');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Jefe de servicio clínico','Jefe de servicio clínico');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Secretaria servicio clínico','Secretaria servicio clínico');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Jefes de departamento','Jefes de departamento');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Director general','Director general');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Coordinador','Coordinador');
INSERT INTO gts_db.roles (nombre,descripcion) VALUES ('Inspector','Inspector');
INSERT INTO gts_db.tipo_doc_identidades (nombre) VALUES ('DNI');
INSERT INTO gts_db.tipo_doc_identidades (nombre) VALUES ('Carnet de Extranjeria');
INSERT INTO gts_db.tipo_fallas (nombre) VALUES ('Eléctrica');
INSERT INTO gts_db.tipo_fallas (nombre) VALUES ('Mecánica');
INSERT INTO gts_db.tipo_fallas (nombre) VALUES ('Electrónica');
INSERT INTO gts_db.tipo_fallas (nombre) VALUES ('Operación');
INSERT INTO gts_db.tipo_fallas (nombre) VALUES ('Re-reparación');
INSERT INTO gts_db.tipo_fallas (nombre) VALUES ('Otros');
INSERT INTO gts_db.prioridades (nombre) VALUES ('Normal');
INSERT INTO gts_db.prioridades (nombre) VALUES ('Urgente');
INSERT INTO gts_db.prioridades (nombre) VALUES ('Critica');
INSERT INTO gts_db.tipo_actas (nombre) VALUES ('Conformidad del Proveedor');
INSERT INTO gts_db.tipo_areas (nombre,descripcion) VALUES ('Departamento','Departamento');
INSERT INTO gts_db.tipo_areas (nombre,descripcion) VALUES ('Unidad','Unidad');
INSERT INTO gts_db.tipo_servicios (nombre,descripcion) VALUES ('Servicio Clinico','Servicio Clinico');
INSERT INTO gts_db.tipo_servicios (nombre,descripcion) VALUES ('Servicio No Clinico','Servicio No Clinico');
INSERT INTO gts_db.tipo_activos (nombre,descripcion) VALUES ('Bien','Bien');
INSERT INTO gts_db.tipo_activos (nombre,descripcion) VALUES ('Tecnologia de Salud','Tecnologia de Salud');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Contratos','Contratos firmados que pueden incluir servicios y/o equipos');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Manuales','Manuales de funcionamiento y de mantenimiento');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Libros','Libros');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Normas','Normas');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Politicas institucionales','Politicas institucionales del hospital');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Certificado de Funcionalidad','Certificado de Funcionalidad');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Termino de Referencia','Término de Referencia');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Reporte de Necesidad','Reporte de Necesidad');
INSERT INTO gts_db.tipo_documentos (nombre,descripcion) VALUES ('Acta de Conformidad','Acta de Conformidad');
INSERT INTO gts_db.tipo_reporte_instalaciones (nombre,descripcion) VALUES ('Entorno Concluido','Entorno Concluido');
INSERT INTO gts_db.tipo_reporte_instalaciones (nombre,descripcion) VALUES ('Equipo Funcional','Equipo Funcional');
INSERT INTO gts_db.tipo_solicitud_compras (nombre,descripcion) VALUES ('Compra','Compra');
INSERT INTO gts_db.tipo_solicitud_compras (nombre,descripcion) VALUES ('Almacen','Almacen');
INSERT INTO gts_db.tipo_solicitud_compras (nombre,descripcion) VALUES ('Reemplazo','Reemplazo');
INSERT INTO gts_db.tablas (nombre_tabla) VALUES ('estado_general');
INSERT INTO gts_db.tablas (nombre_tabla) VALUES ('estado_activo');
INSERT INTO gts_db.tablas (nombre_tabla) VALUES ('estado_ot');
INSERT INTO gts_db.tablas (nombre_tabla) VALUES ('estado_sot');
INSERT INTO gts_db.tablas (nombre_tabla) VALUES ('estado_solicitud_compra');
INSERT INTO gts_db.tablas (nombre_tabla) VALUES ('estado_actividad_realizada');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Activo','1');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Inactivo','1');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Operativo Calibrado','2');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Operativo no calibrado','2');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Inoperativo por insumo','2');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Inoperativo por mantenimiento','2');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Inoperativo por repuesto','2');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('De baja','2');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Pendiente','3');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Exceso de demanda por usuario','3');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('No ubicado en el servicio','3');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Inoperativo por repuesto','3');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Mantenimiento ejecutado','3');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Pendiente','4');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Aprobada','4');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Falsa Alarma','4');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Solución Menor','4');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Solicitado','5');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Atendido','5');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Comprado','5');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Recibido','5');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Realizado','6');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('No realizado','6');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('En Mantenimiento','2');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Reprogramación','3');
INSERT INTO gts_db.estados (nombre,idtabla) VALUES ('Mal Ingreso','4');
INSERT INTO gts_db.areas (nombre,descripcion,idtipo_area,idestado) VALUES ('Obstetricia y Perinatologia','Obstetricia y Perinatologia','1','1');
INSERT INTO gts_db.areas (nombre,descripcion,idtipo_area,idestado) VALUES ('Ginecologia','Ginecologia','1','1');
INSERT INTO gts_db.areas (nombre,descripcion,idtipo_area,idestado) VALUES ('Cuidados Criticos','Cuidados Criticos','1','1');
INSERT INTO gts_db.areas (nombre,descripcion,idtipo_area,idestado) VALUES ('Neonatologia','Neonatologia','1','1');
INSERT INTO gts_db.users (username,password,email,remember_token,nombre,apellido_pat,apellido_mat,fecha_nacimiento,genero,numero_doc_identidad,idrol,idarea,idtipo_documento) VALUES ('gts_webmaster','$2y$10$YSwHz1VNwKl3z7iKVB8k4uxbYGIwNudoETrnZMo0pPG0F16d5SpC.','gts.desarrollo@gmail.com','','gts','webmaster','webmaster','42013','M','11223344','1','1','1');
INSERT INTO gts_db.users (username,password,email,remember_token,nombre,apellido_pat,apellido_mat,fecha_nacimiento,genero,numero_doc_identidad,idrol,idarea,idtipo_documento) VALUES ('gts_lmiranda','$2y$10$YSwHz1VNwKl3z7iKVB8k4uxbYGIwNudoETrnZMo0pPG0F16d5SpC.','lmirandad@pucp.pe','','Luis Miguel','Miranda','Dulanto','33972','M','72299020','2','2','1');
INSERT INTO gts_db.users (username,password,email,remember_token,nombre,apellido_pat,apellido_mat,fecha_nacimiento,genero,numero_doc_identidad,idrol,idarea,idtipo_documento) VALUES ('gts_emerino','$2y$10$YSwHz1VNwKl3z7iKVB8k4uxbYGIwNudoETrnZMo0pPG0F16d5SpC.','merinoe236@gmail.com','','Eduardo','Merino','Tejada','33485','M','12345678','3','3','1');
INSERT INTO gts_db.users (username,password,email,remember_token,nombre,apellido_pat,apellido_mat,fecha_nacimiento,genero,numero_doc_identidad,idrol,idarea,idtipo_documento) VALUES ('gts_ktakayama','$2y$10$YSwHz1VNwKl3z7iKVB8k4uxbYGIwNudoETrnZMo0pPG0F16d5SpC.','takayama.k@pucp.edu.pe','','Kei','Takayama','Nakasato','16/12/1991','M','98765425','1','4','1');
INSERT INTO gts_db.users (username,password,email,remember_token,nombre,apellido_pat,apellido_mat,fecha_nacimiento,genero,numero_doc_identidad,idrol,idarea,idtipo_documento) VALUES ('gts_gcoronado','$2y$10$YSwHz1VNwKl3z7iKVB8k4uxbYGIwNudoETrnZMo0pPG0F16d5SpC.','gustavo.coronado@pucp.pe','','Gustavo','Coronado','Altamirano','24/02/1988','M','10203040','2','1','1');
INSERT INTO gts_db.servicios (nombre,descripcion,idtipo_servicios,idarea,idestado,id_usuario_responsable) VALUES ('Recuperacion Post-Anestesia','Recuperacion Post-Anestesia','1','1','1','1');
INSERT INTO gts_db.servicios (nombre,descripcion,idtipo_servicios,idarea,idestado,id_usuario_responsable) VALUES ('Anatomia Patologica','Anatomia Patologica','1','2','1','2');
INSERT INTO gts_db.servicios (nombre,descripcion,idtipo_servicios,idarea,idestado,id_usuario_responsable) VALUES ('Cocina','Cocina','2','3','1','3');
INSERT INTO gts_db.servicios (nombre,descripcion,idtipo_servicios,idarea,idestado,id_usuario_responsable) VALUES ('Lavanderia','Lavanderia','2','4','1','4');
INSERT INTO gts_db.motivo_retiros (nombre) VALUES ('Obsolescencia Tecnológica');
INSERT INTO gts_db.motivo_retiros (nombre) VALUES ('Costos de Reparación o Mantenimiento');
INSERT INTO gts_db.motivo_retiros (nombre) VALUES ('Antigüedad');
INSERT INTO gts_db.motivo_retiros (nombre) VALUES ('Eventos Adversos e Incidentes');
INSERT INTO gts_db.motivo_retiros (nombre) VALUES ('Disponibilidad de repuestos, accesorios y consumibles');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('1','Paper');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('2','Normas');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('3','Regulaciones');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('4','Protocolos');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('5','Manuales');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('6','Libros');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('7','Tesis');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('8','Estudios');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('9','Publicaciones');
INSERT INTO gts_db.tipo_busqueda_infos (idtipo_busqueda_info,nombre) VALUES ('10','Otros');