/*TIPOS*/

INSERT INTO rh_tipos (id, nombre) VALUES ('1','Capacitacion a usuarios de equipos nuevos');
INSERT INTO rh_tipos (id, nombre) VALUES ('2','Capacitaciones técnicas de equipos nuevos');
INSERT INTO rh_tipos (id, nombre) VALUES ('3','Capacitaciones de salud ocupacional');

/*MODALIDADES*/

INSERT INTO rh_modalidades (id, nombre) VALUES ('1','Virtual');
INSERT INTO rh_modalidades (id, nombre) VALUES ('2','Presencial');

/*PAISES*/

INSERT INTO paises (id, nombre) VALUES ('1','Afganistán');
INSERT INTO paises (id, nombre) VALUES ('2','Akrotiri');
INSERT INTO paises (id, nombre) VALUES ('3','Albania');
INSERT INTO paises (id, nombre) VALUES ('4','Alemania');
INSERT INTO paises (id, nombre) VALUES ('5','Andorra');
INSERT INTO paises (id, nombre) VALUES ('6','Angola');
INSERT INTO paises (id, nombre) VALUES ('7','Anguila');
INSERT INTO paises (id, nombre) VALUES ('8','Antártida');
INSERT INTO paises (id, nombre) VALUES ('9','Antigua y Barbuda');
INSERT INTO paises (id, nombre) VALUES ('10','Antillas Neerlandesas');
INSERT INTO paises (id, nombre) VALUES ('11','Arabia Saudí');
INSERT INTO paises (id, nombre) VALUES ('12','Arctic Ocean');
INSERT INTO paises (id, nombre) VALUES ('13','Argelia');
INSERT INTO paises (id, nombre) VALUES ('14','Argentina');
INSERT INTO paises (id, nombre) VALUES ('15','Armenia');
INSERT INTO paises (id, nombre) VALUES ('16','Aruba');
INSERT INTO paises (id, nombre) VALUES ('17','Ashmore and Cartier Islands');
INSERT INTO paises (id, nombre) VALUES ('18','Atlantic Ocean');
INSERT INTO paises (id, nombre) VALUES ('19','Australia');
INSERT INTO paises (id, nombre) VALUES ('20','Austria');
INSERT INTO paises (id, nombre) VALUES ('21','Azerbaiyán');
INSERT INTO paises (id, nombre) VALUES ('22','Bahamas');
INSERT INTO paises (id, nombre) VALUES ('23','Bahráin');
INSERT INTO paises (id, nombre) VALUES ('24','Bangladesh');
INSERT INTO paises (id, nombre) VALUES ('25','Barbados');
INSERT INTO paises (id, nombre) VALUES ('26','Bélgica');
INSERT INTO paises (id, nombre) VALUES ('27','Belice');
INSERT INTO paises (id, nombre) VALUES ('28','Benín');
INSERT INTO paises (id, nombre) VALUES ('29','Bermudas');
INSERT INTO paises (id, nombre) VALUES ('30','Bielorrusia');
INSERT INTO paises (id, nombre) VALUES ('31','Birmania Myanmar');
INSERT INTO paises (id, nombre) VALUES ('32','Bolivia');
INSERT INTO paises (id, nombre) VALUES ('33','Bosnia y Hercegovina');
INSERT INTO paises (id, nombre) VALUES ('34','Botsuana');
INSERT INTO paises (id, nombre) VALUES ('35','Brasil');
INSERT INTO paises (id, nombre) VALUES ('36','Brunéi');
INSERT INTO paises (id, nombre) VALUES ('37','Bulgaria');
INSERT INTO paises (id, nombre) VALUES ('38','Burkina Faso');
INSERT INTO paises (id, nombre) VALUES ('39','Burundi');
INSERT INTO paises (id, nombre) VALUES ('40','Bután');
INSERT INTO paises (id, nombre) VALUES ('41','Cabo Verde');
INSERT INTO paises (id, nombre) VALUES ('42','Camboya');
INSERT INTO paises (id, nombre) VALUES ('43','Camerún');
INSERT INTO paises (id, nombre) VALUES ('44','Canadá');
INSERT INTO paises (id, nombre) VALUES ('45','Chad');
INSERT INTO paises (id, nombre) VALUES ('46','Chile');
INSERT INTO paises (id, nombre) VALUES ('47','China');
INSERT INTO paises (id, nombre) VALUES ('48','Chipre');
INSERT INTO paises (id, nombre) VALUES ('49','Clipperton Island');
INSERT INTO paises (id, nombre) VALUES ('50','Colombia');
INSERT INTO paises (id, nombre) VALUES ('51','Comoras');
INSERT INTO paises (id, nombre) VALUES ('52','Congo');
INSERT INTO paises (id, nombre) VALUES ('53','Coral Sea Islands');
INSERT INTO paises (id, nombre) VALUES ('54','Corea del Norte');
INSERT INTO paises (id, nombre) VALUES ('55','Corea del Sur');
INSERT INTO paises (id, nombre) VALUES ('56','Costa de Marfil');
INSERT INTO paises (id, nombre) VALUES ('57','Costa Rica');
INSERT INTO paises (id, nombre) VALUES ('58','Croacia');
INSERT INTO paises (id, nombre) VALUES ('59','Cuba');
INSERT INTO paises (id, nombre) VALUES ('60','Dhekelia');
INSERT INTO paises (id, nombre) VALUES ('61','Dinamarca');
INSERT INTO paises (id, nombre) VALUES ('62','Dominica');
INSERT INTO paises (id, nombre) VALUES ('63','Ecuador');
INSERT INTO paises (id, nombre) VALUES ('64','Egipto');
INSERT INTO paises (id, nombre) VALUES ('65','El Salvador');
INSERT INTO paises (id, nombre) VALUES ('66','El Vaticano');
INSERT INTO paises (id, nombre) VALUES ('67','Emiratos Árabes Unidos');
INSERT INTO paises (id, nombre) VALUES ('68','Eritrea');
INSERT INTO paises (id, nombre) VALUES ('69','Eslovaquia');
INSERT INTO paises (id, nombre) VALUES ('70','Eslovenia');
INSERT INTO paises (id, nombre) VALUES ('71','España');
INSERT INTO paises (id, nombre) VALUES ('72','Estados Unidos');
INSERT INTO paises (id, nombre) VALUES ('73','Estonia');
INSERT INTO paises (id, nombre) VALUES ('74','Etiopía');
INSERT INTO paises (id, nombre) VALUES ('75','Filipinas');
INSERT INTO paises (id, nombre) VALUES ('76','Finlandia');
INSERT INTO paises (id, nombre) VALUES ('77','Fiyi');
INSERT INTO paises (id, nombre) VALUES ('78','Francia');
INSERT INTO paises (id, nombre) VALUES ('79','Gabón');
INSERT INTO paises (id, nombre) VALUES ('80','Gambia');
INSERT INTO paises (id, nombre) VALUES ('81','Gaza Strip');
INSERT INTO paises (id, nombre) VALUES ('82','Georgia');
INSERT INTO paises (id, nombre) VALUES ('83','Ghana');
INSERT INTO paises (id, nombre) VALUES ('84','Gibraltar');
INSERT INTO paises (id, nombre) VALUES ('85','Granada');
INSERT INTO paises (id, nombre) VALUES ('86','Grecia');
INSERT INTO paises (id, nombre) VALUES ('87','Groenlandia');
INSERT INTO paises (id, nombre) VALUES ('88','Guam');
INSERT INTO paises (id, nombre) VALUES ('89','Guatemala');
INSERT INTO paises (id, nombre) VALUES ('90','Gernsey');
INSERT INTO paises (id, nombre) VALUES ('91','Guinea');
INSERT INTO paises (id, nombre) VALUES ('92','Guinea Ecuatorial');
INSERT INTO paises (id, nombre) VALUES ('93','Guinea-Bissau');
INSERT INTO paises (id, nombre) VALUES ('94','Guyana');
INSERT INTO paises (id, nombre) VALUES ('95','Haitií');
INSERT INTO paises (id, nombre) VALUES ('96','Honduras');
INSERT INTO paises (id, nombre) VALUES ('97','Hong Kong');
INSERT INTO paises (id, nombre) VALUES ('98','Hungría');
INSERT INTO paises (id, nombre) VALUES ('99','India');
INSERT INTO paises (id, nombre) VALUES ('100','Indian Ocean');
INSERT INTO paises (id, nombre) VALUES ('101','Indonesia');
INSERT INTO paises (id, nombre) VALUES ('102','Irán');
INSERT INTO paises (id, nombre) VALUES ('103','Iraq');
INSERT INTO paises (id, nombre) VALUES ('104','Irlanda');
INSERT INTO paises (id, nombre) VALUES ('105','Isla Bouvet');
INSERT INTO paises (id, nombre) VALUES ('106','Isla Christmas');
INSERT INTO paises (id, nombre) VALUES ('107','Isla Norfolk');
INSERT INTO paises (id, nombre) VALUES ('108','Islandia');
INSERT INTO paises (id, nombre) VALUES ('109','Islas Caimán');
INSERT INTO paises (id, nombre) VALUES ('110','Islas Cocos');
INSERT INTO paises (id, nombre) VALUES ('111','Islas Cook');
INSERT INTO paises (id, nombre) VALUES ('112','Islas Feroe');
INSERT INTO paises (id, nombre) VALUES ('113','Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO paises (id, nombre) VALUES ('114','Islas Heard y McDonalds');
INSERT INTO paises (id, nombre) VALUES ('115','Islas Malvinas');
INSERT INTO paises (id, nombre) VALUES ('116','Islas Marianas del Norte');
INSERT INTO paises (id, nombre) VALUES ('117','Islas Marshall');
INSERT INTO paises (id, nombre) VALUES ('118','Islas Pitcairn');
INSERT INTO paises (id, nombre) VALUES ('119','Islas Salomón');
INSERT INTO paises (id, nombre) VALUES ('120','Islas Turcas y Caicos');
INSERT INTO paises (id, nombre) VALUES ('121','Islas Vírgenes Americanas');
INSERT INTO paises (id, nombre) VALUES ('122','Islas Vírgenes Británicas');
INSERT INTO paises (id, nombre) VALUES ('123','Israel');
INSERT INTO paises (id, nombre) VALUES ('124','Italia');
INSERT INTO paises (id, nombre) VALUES ('125','Jamaica');
INSERT INTO paises (id, nombre) VALUES ('126','Jan Mayen');
INSERT INTO paises (id, nombre) VALUES ('127','Japón');
INSERT INTO paises (id, nombre) VALUES ('128','Jersey');
INSERT INTO paises (id, nombre) VALUES ('129','Jordania');
INSERT INTO paises (id, nombre) VALUES ('130','Kazajistán');
INSERT INTO paises (id, nombre) VALUES ('131','Kenia');
INSERT INTO paises (id, nombre) VALUES ('132','Kirguizistán');
INSERT INTO paises (id, nombre) VALUES ('133','Kiribati');
INSERT INTO paises (id, nombre) VALUES ('134','Kuwait');
INSERT INTO paises (id, nombre) VALUES ('135','Laos');
INSERT INTO paises (id, nombre) VALUES ('136','Lesoto');
INSERT INTO paises (id, nombre) VALUES ('137','Letonia');
INSERT INTO paises (id, nombre) VALUES ('138','Líbano');
INSERT INTO paises (id, nombre) VALUES ('139','Liberia');
INSERT INTO paises (id, nombre) VALUES ('140','Libia');
INSERT INTO paises (id, nombre) VALUES ('141','Liechtenstein');
INSERT INTO paises (id, nombre) VALUES ('142','Lituania');
INSERT INTO paises (id, nombre) VALUES ('143','Luxemburgo');
INSERT INTO paises (id, nombre) VALUES ('144','Macao');
INSERT INTO paises (id, nombre) VALUES ('145','Macedonia');
INSERT INTO paises (id, nombre) VALUES ('146','Madagascar');
INSERT INTO paises (id, nombre) VALUES ('147','Malasia');
INSERT INTO paises (id, nombre) VALUES ('148','Malaui');
INSERT INTO paises (id, nombre) VALUES ('149','Maldivas');
INSERT INTO paises (id, nombre) VALUES ('150','Malí');
INSERT INTO paises (id, nombre) VALUES ('151','Malta');
INSERT INTO paises (id, nombre) VALUES ('152','Man, Isle of');
INSERT INTO paises (id, nombre) VALUES ('153','Marruecos');
INSERT INTO paises (id, nombre) VALUES ('154','Mauricio');
INSERT INTO paises (id, nombre) VALUES ('155','Mauritania');
INSERT INTO paises (id, nombre) VALUES ('156','Mayotte');
INSERT INTO paises (id, nombre) VALUES ('157','México');
INSERT INTO paises (id, nombre) VALUES ('158','Micronesia');
INSERT INTO paises (id, nombre) VALUES ('159','Moldavia');
INSERT INTO paises (id, nombre) VALUES ('160','Mónaco');
INSERT INTO paises (id, nombre) VALUES ('161','Mongolia');
INSERT INTO paises (id, nombre) VALUES ('162','Montserrat');
INSERT INTO paises (id, nombre) VALUES ('163','Mozambique');
INSERT INTO paises (id, nombre) VALUES ('164','Namibia');
INSERT INTO paises (id, nombre) VALUES ('165','Nauru');
INSERT INTO paises (id, nombre) VALUES ('166','Navassa Island');
INSERT INTO paises (id, nombre) VALUES ('167','Nepal');
INSERT INTO paises (id, nombre) VALUES ('168','Nicaragua');
INSERT INTO paises (id, nombre) VALUES ('169','Niger');
INSERT INTO paises (id, nombre) VALUES ('170','Nigeria');
INSERT INTO paises (id, nombre) VALUES ('171','Niue');
INSERT INTO paises (id, nombre) VALUES ('172','Noregua');
INSERT INTO paises (id, nombre) VALUES ('173','Nueva Caledonia');
INSERT INTO paises (id, nombre) VALUES ('174','Nueva Zelanda');
INSERT INTO paises (id, nombre) VALUES ('175','Omán');
INSERT INTO paises (id, nombre) VALUES ('176','Pacific Ocean');
INSERT INTO paises (id, nombre) VALUES ('177','Países Bajos');
INSERT INTO paises (id, nombre) VALUES ('178','Pakistán');
INSERT INTO paises (id, nombre) VALUES ('179','Palaos');
INSERT INTO paises (id, nombre) VALUES ('180','Panamá');
INSERT INTO paises (id, nombre) VALUES ('181','Papúa-Nueva Guinea');
INSERT INTO paises (id, nombre) VALUES ('182','Paracel Islands');
INSERT INTO paises (id, nombre) VALUES ('183','Paraguay');
INSERT INTO paises (id, nombre) VALUES ('184','Perú');
INSERT INTO paises (id, nombre) VALUES ('185','Polinesia Francesa');
INSERT INTO paises (id, nombre) VALUES ('186','Polonia');
INSERT INTO paises (id, nombre) VALUES ('187','Portugal');
INSERT INTO paises (id, nombre) VALUES ('188','Puerto Rico');
INSERT INTO paises (id, nombre) VALUES ('189','Qatar');
INSERT INTO paises (id, nombre) VALUES ('190','Reino Unido');
INSERT INTO paises (id, nombre) VALUES ('191','Republica Centroafricana');
INSERT INTO paises (id, nombre) VALUES ('192','Republica Checa');
INSERT INTO paises (id, nombre) VALUES ('193','República Democrática del Congo');
INSERT INTO paises (id, nombre) VALUES ('194','República Dominicana');
INSERT INTO paises (id, nombre) VALUES ('195','Ruanda');
INSERT INTO paises (id, nombre) VALUES ('196','Rumania');
INSERT INTO paises (id, nombre) VALUES ('197','Rusia');
INSERT INTO paises (id, nombre) VALUES ('198','Sáhara Occidental');
INSERT INTO paises (id, nombre) VALUES ('199','Samoa');
INSERT INTO paises (id, nombre) VALUES ('200','Samoa Americana');
INSERT INTO paises (id, nombre) VALUES ('201','San Cristóbal y Nieves');
INSERT INTO paises (id, nombre) VALUES ('202','San Marino');
INSERT INTO paises (id, nombre) VALUES ('203','San Pedro y Miquelón');
INSERT INTO paises (id, nombre) VALUES ('204','San Vicente y las Granadinas');
INSERT INTO paises (id, nombre) VALUES ('205','Santa Helena');
INSERT INTO paises (id, nombre) VALUES ('206','Santa Lúcia');
INSERT INTO paises (id, nombre) VALUES ('207','Santo Tomé y Príncipe');
INSERT INTO paises (id, nombre) VALUES ('208','Senegal');
INSERT INTO paises (id, nombre) VALUES ('209','Seychelles');
INSERT INTO paises (id, nombre) VALUES ('210','Sierra Leones');
INSERT INTO paises (id, nombre) VALUES ('211','Signapur');
INSERT INTO paises (id, nombre) VALUES ('212','Siria');
INSERT INTO paises (id, nombre) VALUES ('213','Somalia');
INSERT INTO paises (id, nombre) VALUES ('214','Southern Ocean');
INSERT INTO paises (id, nombre) VALUES ('215','Spratly Islands');
INSERT INTO paises (id, nombre) VALUES ('216','Sri Lanka');
INSERT INTO paises (id, nombre) VALUES ('217','Suazilandia');
INSERT INTO paises (id, nombre) VALUES ('218','Sudáfrica');
INSERT INTO paises (id, nombre) VALUES ('219','Sudán');
INSERT INTO paises (id, nombre) VALUES ('220','Suecia');
INSERT INTO paises (id, nombre) VALUES ('221','Suiza');
INSERT INTO paises (id, nombre) VALUES ('222','Surinam');
INSERT INTO paises (id, nombre) VALUES ('223','Svalbard y Jan Mayen');
INSERT INTO paises (id, nombre) VALUES ('224','Tailandia');
INSERT INTO paises (id, nombre) VALUES ('225','Taiwán');
INSERT INTO paises (id, nombre) VALUES ('226','Tanzania');
INSERT INTO paises (id, nombre) VALUES ('227','Tayikistán');
INSERT INTO paises (id, nombre) VALUES ('228','Territorio Británico del Océano Indico');
INSERT INTO paises (id, nombre) VALUES ('229','Territorios Australes Franceses');
INSERT INTO paises (id, nombre) VALUES ('230','Timor Oriental');
INSERT INTO paises (id, nombre) VALUES ('231','Togo');
INSERT INTO paises (id, nombre) VALUES ('232','Tokelau');
INSERT INTO paises (id, nombre) VALUES ('233','Tonga');
INSERT INTO paises (id, nombre) VALUES ('234','Trinidad y Tobago');
INSERT INTO paises (id, nombre) VALUES ('235','Túnez');
INSERT INTO paises (id, nombre) VALUES ('236','Turkmenistán');
INSERT INTO paises (id, nombre) VALUES ('237','Turquía');
INSERT INTO paises (id, nombre) VALUES ('238','Tuvalu');
INSERT INTO paises (id, nombre) VALUES ('239','Ucrania');
INSERT INTO paises (id, nombre) VALUES ('240','Uganda');
INSERT INTO paises (id, nombre) VALUES ('241','Unión Europea');
INSERT INTO paises (id, nombre) VALUES ('242','Uruguay');
INSERT INTO paises (id, nombre) VALUES ('243','Uzbekistán');
INSERT INTO paises (id, nombre) VALUES ('244','Vanatu');
INSERT INTO paises (id, nombre) VALUES ('245','Venezuela');
INSERT INTO paises (id, nombre) VALUES ('246','Vietnam');
INSERT INTO paises (id, nombre) VALUES ('247','Wake Island');
INSERT INTO paises (id, nombre) VALUES ('248','Wallis y Futuna');
INSERT INTO paises (id, nombre) VALUES ('249','West Bank');
INSERT INTO paises (id, nombre) VALUES ('250','World');
INSERT INTO paises (id, nombre) VALUES ('251','Yemen');
INSERT INTO paises (id, nombre) VALUES ('252','Yibuti');
INSERT INTO paises (id, nombre) VALUES ('253','Zambia');
INSERT INTO paises (id, nombre) VALUES ('254','Zimbabue');

/* IDIOMAS */

INSERT INTO idiomas (id, nombre) VALUES ('1','Aimara');
INSERT INTO idiomas (id, nombre) VALUES ('2','Aleman');
INSERT INTO idiomas (id, nombre) VALUES ('3','Ashaninka');
INSERT INTO idiomas (id, nombre) VALUES ('4','Arabe');
INSERT INTO idiomas (id, nombre) VALUES ('5','Awajun');
INSERT INTO idiomas (id, nombre) VALUES ('6','Bulgaro');
INSERT INTO idiomas (id, nombre) VALUES ('7','Catalan');
INSERT INTO idiomas (id, nombre) VALUES ('8','Checo');
INSERT INTO idiomas (id, nombre) VALUES ('9','Chikitano');
INSERT INTO idiomas (id, nombre) VALUES ('10','Chino');
INSERT INTO idiomas (id, nombre) VALUES ('11','Chiriguano');
INSERT INTO idiomas (id, nombre) VALUES ('12','Chol');
INSERT INTO idiomas (id, nombre) VALUES ('13','Coreano');
INSERT INTO idiomas (id, nombre) VALUES ('14','Creole');
INSERT INTO idiomas (id, nombre) VALUES ('15','Danes');
INSERT INTO idiomas (id, nombre) VALUES ('16','Eslovaco');
INSERT INTO idiomas (id, nombre) VALUES ('17','Español');
INSERT INTO idiomas (id, nombre) VALUES ('18','Frances');
INSERT INTO idiomas (id, nombre) VALUES ('19','Garifuna');
INSERT INTO idiomas (id, nombre) VALUES ('20','Griego');
INSERT INTO idiomas (id, nombre) VALUES ('21','Guarani');
INSERT INTO idiomas (id, nombre) VALUES ('22','Guarayo');
INSERT INTO idiomas (id, nombre) VALUES ('23','Hebreo');
INSERT INTO idiomas (id, nombre) VALUES ('24','Hindu');
INSERT INTO idiomas (id, nombre) VALUES ('25','Holandes');
INSERT INTO idiomas (id, nombre) VALUES ('26','Hungaro');
INSERT INTO idiomas (id, nombre) VALUES ('27','Ingles');
INSERT INTO idiomas (id, nombre) VALUES ('28','Italiano');
INSERT INTO idiomas (id, nombre) VALUES ('29','Japones');
INSERT INTO idiomas (id, nombre) VALUES ('30','Kayapa');
INSERT INTO idiomas (id, nombre) VALUES ('31','Kichwa');
INSERT INTO idiomas (id, nombre) VALUES ('32','Latin');
INSERT INTO idiomas (id, nombre) VALUES ('33','Lituano');
INSERT INTO idiomas (id, nombre) VALUES ('34','Macushi');
INSERT INTO idiomas (id, nombre) VALUES ('35','Misquito');
INSERT INTO idiomas (id, nombre) VALUES ('36','Polaco');
INSERT INTO idiomas (id, nombre) VALUES ('37','Portugues');
INSERT INTO idiomas (id, nombre) VALUES ('38','Quechua');
INSERT INTO idiomas (id, nombre) VALUES ('39','Rumano');
INSERT INTO idiomas (id, nombre) VALUES ('40','Shipibo-Conibo');
INSERT INTO idiomas (id, nombre) VALUES ('41','Sueco');
INSERT INTO idiomas (id, nombre) VALUES ('42','Tseltal');
INSERT INTO idiomas (id, nombre) VALUES ('43','Tsafiki');
INSERT INTO idiomas (id, nombre) VALUES ('44','Tzotzil');
INSERT INTO idiomas (id, nombre) VALUES ('45','Wapishana');
INSERT INTO idiomas (id, nombre) VALUES ('46','Yanomam');
