INSERT INTO tipo_reporte_paac (idtipo_reporte_paac,nombre) VALUES ('1','R-PAAC');
INSERT INTO tipo_reporte_paac (idtipo_reporte_paac,nombre) VALUES ('2','R-PAAC Complementario');
INSERT INTO tipo_reporte_cn (idtipo_reporte_cn,nombre) VALUES ('1','R-CN Anual');
INSERT INTO tipo_reporte_cn (idtipo_reporte_cn,nombre) VALUES ('2','R-CN Inmediato');
INSERT INTO tipo_reporte_cn (idtipo_reporte_cn,nombre) VALUES ('3','R-CN Mediano y Largo Plazo');
INSERT INTO tipo_reporte_etes (idtipo_reporte_etes,nombre) VALUES ('1','R-ETES Clínico');
INSERT INTO tipo_reporte_etes (idtipo_reporte_etes,nombre) VALUES ('2','R-ETES Tecnológico');
INSERT INTO tipo_reporte_etes (idtipo_reporte_etes,nombre) VALUES ('3','R-ETES Económico');
INSERT INTO tipo_referencia (idtipo_referencia,nombre) VALUES ('1','Cotización');
INSERT INTO tipo_referencia (idtipo_referencia,nombre) VALUES ('2','SEACE');
INSERT INTO tipo_documentospaac (idtipo_documentospaac,nombre) VALUES ('1','ASIGNACIÓN DE COSTOS PARA PAAC');
INSERT INTO tipo_documentospaac (idtipo_documentospaac,nombre) VALUES ('2','ASIGNACIÓN DE COSTOS PARA PAAC COMPLEMENTARIO');
INSERT INTO tipo_documentospaac (idtipo_documentospaac,nombre) VALUES ('3','PRESUPUESTO PARA PAAC');
INSERT INTO tipo_documentospaac (idtipo_documentospaac,nombre) VALUES ('4','PRESUPUESTO PARA PAAC COMPLEMENTARIO');
INSERT INTO tipo_documentospaac (idtipo_documentospaac,nombre) VALUES ('5','PAAC');
INSERT INTO tipo_documentospaac (idtipo_documentospaac,nombre) VALUES ('6','PAAC COMPLEMENTARIO');
INSERT INTO tipo_documentosplandirector (idtipo_documentosplandirector,nombre) VALUES ('1','PLAN DIRECTOR');
INSERT INTO tipo_documentosplandirector (idtipo_documentosplandirector,nombre) VALUES ('2','POLÍTICAS INSTITUCIONALES');
INSERT INTO tipo_documentosplandirector (idtipo_documentosplandirector,nombre) VALUES ('3','PLAN ESTRATÉGICO INSTITUCIONAL EN TS');
INSERT INTO tipo_documentosplandirector (idtipo_documentosplandirector,nombre) VALUES ('4','PLAN OPERATIVO ANUAL');
