-- MySQL Script generated by MySQL Workbench
-- 11/26/15 10:58:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gts_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gts_db` ;

-- -----------------------------------------------------
-- Schema gts_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gts_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gts_db` ;

-- -----------------------------------------------------
-- Table `gts_db`.`tipo_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_areas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_areas` (
  `idtipo_area` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_area`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`tablas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tablas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tablas` (
  `idtabla` INT NOT NULL AUTO_INCREMENT,
  `nombre_tabla` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`idtabla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`estados` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`estados` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `idtabla` INT NOT NULL,
  PRIMARY KEY (`idestado`),
  INDEX `fk_estados_tablas1_idx` (`idtabla` ASC),
  CONSTRAINT `fk_estados_tablas1`
    FOREIGN KEY (`idtabla`)
    REFERENCES `gts_db`.`tablas` (`idtabla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`areas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`areas` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idtipo_area` INT NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idarea`),
  INDEX `fk_areas_tipo_areas1_idx` (`idtipo_area` ASC),
  INDEX `fk_areas_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_areas_tipo_areas1`
    FOREIGN KEY (`idtipo_area`)
    REFERENCES `gts_db`.`tipo_areas` (`idtipo_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_areas_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_documentos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_documentos` (
  `idtipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_reporte_instalaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_reporte_instalaciones` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_reporte_instalaciones` (
  `idtipo_reporte_instalacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_reporte_instalacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`roles` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_doc_identidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_doc_identidades` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_doc_identidades` (
  `idtipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`users` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `remember_token` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido_pat` VARCHAR(200) NOT NULL,
  `apellido_mat` VARCHAR(200) NOT NULL,
  `fecha_nacimiento` TIMESTAMP NULL DEFAULT NULL,
  `genero` VARCHAR(1) NOT NULL,
  `numero_doc_identidad` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idrol` INT(11) NOT NULL,
  `idarea` INT(11) NOT NULL,
  `idtipo_documento` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`idrol` ASC),
  INDEX `fk_users_areas1_idx` (`idarea` ASC),
  INDEX `fk_users_tipo_doc_identidades1_idx` (`idtipo_documento` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`idrol`)
    REFERENCES `gts_db`.`roles` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_areas1`
    FOREIGN KEY (`idarea`)
    REFERENCES `gts_db`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_tipo_doc_identidades1`
    FOREIGN KEY (`idtipo_documento`)
    REFERENCES `gts_db`.`tipo_doc_identidades` (`idtipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`proveedores` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(11) NOT NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `nombre_contacto` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_proveedores_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_proveedores_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`reporte_instalaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`reporte_instalaciones` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`reporte_instalaciones` (
  `idreporte_instalacion` INT NOT NULL AUTO_INCREMENT,
  `numero_reporte_abreviatura` VARCHAR(2) NOT NULL,
  `numero_reporte_correlativo` VARCHAR(4) NOT NULL,
  `numero_reporte_anho` VARCHAR(2) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `fecha` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idtipo_reporte_instalacion` INT NOT NULL,
  `idestado` INT NOT NULL,
  `id_responsable` INT NOT NULL,
  `codigo_compra` VARCHAR(45) NULL,
  `idproveedor` INT NOT NULL,
  `idarea` INT NOT NULL,
  `idreporte_instalacion_entorno_concluido` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idreporte_instalacion`),
  INDEX `fk_reporte_instalaciones_tipo_reporte_instalaciones1_idx` (`idtipo_reporte_instalacion` ASC),
  INDEX `fk_reporte_instalaciones_estados1_idx` (`idestado` ASC),
  INDEX `fk_reporte_instalaciones_users1_idx` (`id_responsable` ASC),
  INDEX `fk_reporte_instalaciones_proveedores1_idx` (`idproveedor` ASC),
  INDEX `fk_reporte_instalaciones_areas1_idx` (`idarea` ASC),
  INDEX `fk_reporte_instalaciones_reporte_instalaciones1_idx` (`idreporte_instalacion_entorno_concluido` ASC),
  CONSTRAINT `fk_reporte_instalaciones_tipo_reporte_instalaciones1`
    FOREIGN KEY (`idtipo_reporte_instalacion`)
    REFERENCES `gts_db`.`tipo_reporte_instalaciones` (`idtipo_reporte_instalacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_instalaciones_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_instalaciones_users1`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_instalaciones_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `gts_db`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_instalaciones_areas1`
    FOREIGN KEY (`idarea`)
    REFERENCES `gts_db`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_instalaciones_reporte_instalaciones1`
    FOREIGN KEY (`idreporte_instalacion_entorno_concluido`)
    REFERENCES `gts_db`.`reporte_instalaciones` (`idreporte_instalacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`grupos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`grupos` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `id_responsable` INT(11) NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idgrupo`),
  INDEX `fk_grupos_users1_idx` (`id_responsable` ASC),
  INDEX `fk_grupos_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_grupos_users1`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_servicios` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_servicios` (
  `idtipo_servicios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_servicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`servicios` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`servicios` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idtipo_servicios` INT NOT NULL,
  `idarea` INT(11) NOT NULL,
  `idestado` INT NOT NULL,
  `id_usuario_responsable` INT NOT NULL,
  PRIMARY KEY (`idservicio`),
  INDEX `fk_servicios_tipo_servicios1_idx` (`idtipo_servicios` ASC),
  INDEX `fk_servicios_areas1_idx` (`idarea` ASC),
  INDEX `fk_servicios_estados1_idx` (`idestado` ASC),
  INDEX `fk_servicios_users1_idx` (`id_usuario_responsable` ASC),
  CONSTRAINT `fk_servicios_tipo_servicios1`
    FOREIGN KEY (`idtipo_servicios`)
    REFERENCES `gts_db`.`tipo_servicios` (`idtipo_servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicios_areas1`
    FOREIGN KEY (`idarea`)
    REFERENCES `gts_db`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicios_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicios_users1`
    FOREIGN KEY (`id_usuario_responsable`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`ubicacion_fisicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ubicacion_fisicas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ubicacion_fisicas` (
  `idubicacion_fisica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idubicacion_fisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_activos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_activos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_activos` (
  `idtipo_activo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_activo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`marcas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`marcas` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idmarca`),
  INDEX `fk_marcas_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_marcas_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`familia_activos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`familia_activos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`familia_activos` (
  `idfamilia_activo` INT NOT NULL AUTO_INCREMENT,
  `nombre_equipo` VARCHAR(100) NOT NULL,
  `nombre_siga` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idtipo_activo` INT NOT NULL,
  `idmarca` INT NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idfamilia_activo`),
  INDEX `fk_familia_activos_tipo_activos1_idx` (`idtipo_activo` ASC),
  INDEX `fk_familia_activos_marcas1_idx` (`idmarca` ASC),
  INDEX `fk_familia_activos_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_familia_activos_tipo_activos1`
    FOREIGN KEY (`idtipo_activo`)
    REFERENCES `gts_db`.`tipo_activos` (`idtipo_activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familia_activos_marcas1`
    FOREIGN KEY (`idmarca`)
    REFERENCES `gts_db`.`marcas` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familia_activos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`modelo_activos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`modelo_activos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`modelo_activos` (
  `idmodelo_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idfamilia_activo` INT NOT NULL,
  PRIMARY KEY (`idmodelo_equipo`),
  INDEX `fk_modelo_activos_familia_activos1_idx` (`idfamilia_activo` ASC),
  CONSTRAINT `fk_modelo_activos_familia_activos1`
    FOREIGN KEY (`idfamilia_activo`)
    REFERENCES `gts_db`.`familia_activos` (`idfamilia_activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`activos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`activos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`activos` (
  `idactivo` INT NOT NULL AUTO_INCREMENT,
  `codigo_patrimonial` VARCHAR(100) NOT NULL,
  `numero_serie` VARCHAR(100) NOT NULL,
  `anho_adquisicion` DATE NOT NULL,
  `garantia` INT NOT NULL,
  `costo` FLOAT NULL,
  `codigo_compra` VARCHAR(100) NULL,
  `idgrupo` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `idproveedor` INT NOT NULL,
  `idreporte_instalacion` INT NOT NULL,
  `idubicacion_fisica` INT NOT NULL,
  `idmodelo_equipo` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idactivo`),
  INDEX `fk_activos_grupos1_idx` (`idgrupo` ASC),
  INDEX `fk_activos_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_activos_proveedores1_idx` (`idproveedor` ASC),
  INDEX `fk_activos_reporte_instalaciones1_idx` (`idreporte_instalacion` ASC),
  INDEX `fk_activos_estados1_idx` (`idestado` ASC),
  INDEX `fk_activos_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_activos_modelo_activos1_idx` (`idmodelo_equipo` ASC),
  CONSTRAINT `fk_activos_grupos1`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `gts_db`.`grupos` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `gts_db`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_reporte_instalaciones1`
    FOREIGN KEY (`idreporte_instalacion`)
    REFERENCES `gts_db`.`reporte_instalaciones` (`idreporte_instalacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_modelo_activos1`
    FOREIGN KEY (`idmodelo_equipo`)
    REFERENCES `gts_db`.`modelo_activos` (`idmodelo_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`contratos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`contratos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`contratos` (
  `idcontrato` INT NOT NULL AUTO_INCREMENT,
  `fecha_contrato` TIMESTAMP NOT NULL,
  `idorden_compra` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idproveedor` INT NOT NULL,
  `id_responsable` INT NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idcontrato`),
  INDEX `fk_contratos_proveedores1_idx` (`idproveedor` ASC),
  INDEX `fk_contratos_users1_idx` (`id_responsable` ASC),
  INDEX `fk_contratos_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_contratos_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `gts_db`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_users1`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`reporte_incumplimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`reporte_incumplimientos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`reporte_incumplimientos` (
  `idreporte_incumplimiento` INT NOT NULL AUTO_INCREMENT,
  `numero_reporte_abreviatura` VARCHAR(2) NOT NULL,
  `numero_reporte_correlativo` VARCHAR(4) NOT NULL,
  `numero_reporte_anho` VARCHAR(2) NOT NULL,
  `tipo_reporte` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `descripcion_corta` VARCHAR(100) NULL,
  `descripcion_servicio` VARCHAR(200) NULL,
  `costo_generado` FLOAT NOT NULL,
  `accion_correctiva` VARCHAR(200) NULL,
  `flag_reincidente` INT NOT NULL,
  `acciones` VARCHAR(200) NULL,
  `resultados` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idservicio` INT NOT NULL,
  `idproveedor` INT NOT NULL,
  `id_responsable` INT NOT NULL,
  `id_elaborado` INT NOT NULL,
  `id_autorizado` INT NOT NULL,
  `idestado` INT NOT NULL,
  `codigo_ot` VARCHAR(10) NULL,
  PRIMARY KEY (`idreporte_incumplimiento`),
  INDEX `fk_reporte_incumplimientos_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_reporte_incumplimientos_proveedores1_idx` (`idproveedor` ASC),
  INDEX `fk_reporte_incumplimientos_users1_idx` (`id_responsable` ASC),
  INDEX `fk_reporte_incumplimientos_users2_idx` (`id_elaborado` ASC),
  INDEX `fk_reporte_incumplimientos_users3_idx` (`id_autorizado` ASC),
  INDEX `fk_reporte_incumplimientos_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_reporte_incumplimientos_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_incumplimientos_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `gts_db`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_incumplimientos_users1`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_incumplimientos_users2`
    FOREIGN KEY (`id_elaborado`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_incumplimientos_users3`
    FOREIGN KEY (`id_autorizado`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_incumplimientos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_solicitud_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_solicitud_compras` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_solicitud_compras` (
  `idtipo_solicitud_compra` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_solicitud_compra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`solicitud_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`solicitud_compras` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`solicitud_compras` (
  `idsolicitud_compra` INT NOT NULL AUTO_INCREMENT,
  `codigo_ot` VARCHAR(10) NULL,
  `idtipo_solicitud_compra` INT NOT NULL,
  `idfamilia_activo` INT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `sustento` VARCHAR(500) NULL,
  `idservicio` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `id_responsable` INT NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idsolicitud_compra`),
  INDEX `fk_solicitud_compras_tipo_solicitud_compras1_idx` (`idtipo_solicitud_compra` ASC),
  INDEX `fk_solicitud_compras_familia_activos1_idx` (`idfamilia_activo` ASC),
  INDEX `fk_solicitud_compras_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_solicitud_compras_users1_idx` (`id_responsable` ASC),
  INDEX `fk_solicitud_compras_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_solicitud_compras_tipo_solicitud_compras1`
    FOREIGN KEY (`idtipo_solicitud_compra`)
    REFERENCES `gts_db`.`tipo_solicitud_compras` (`idtipo_solicitud_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_compras_familia_activos1`
    FOREIGN KEY (`idfamilia_activo`)
    REFERENCES `gts_db`.`familia_activos` (`idfamilia_activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_compras_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_compras_users1`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_compras_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_actas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_actas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_actas` (
  `idtipo_acta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_acta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`motivo_retiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`motivo_retiros` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`motivo_retiros` (
  `idmotivo_retiro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idmotivo_retiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`reporte_retiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`reporte_retiros` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`reporte_retiros` (
  `idreporte_retiro` INT NOT NULL AUTO_INCREMENT,
  `reporte_tipo_abreviatura` VARCHAR(2) NULL,
  `reporte_correlativo` VARCHAR(4) NULL,
  `reporte_activo_abreviatura` VARCHAR(2) NULL,
  `idactivo` INT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `idmotivo_retiro` INT NOT NULL,
  `fecha_baja` TIMESTAMP NULL,
  `costo` FLOAT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idreporte_retiro`),
  INDEX `fk_reporte_retiros_activos1_idx` (`idactivo` ASC),
  INDEX `fk_reporte_retiros_motivo_retiros1_idx` (`idmotivo_retiro` ASC),
  CONSTRAINT `fk_reporte_retiros_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_retiros_motivo_retiros1`
    FOREIGN KEY (`idmotivo_retiro`)
    REFERENCES `gts_db`.`motivo_retiros` (`idmotivo_retiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_vmetrologicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_vmetrologicas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_vmetrologicas` (
  `idot_vmetrologica` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(2) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `ot_activo_abreviatura` VARCHAR(2) NULL,
  `numero_ficha` INT NULL,
  `idservicio` INT NOT NULL,
  `id_usuariosolicitante` INT NOT NULL,
  `id_usuarioelaborador` INT NULL,
  `idactivo` INT NOT NULL,
  `idestado_inicial` INT NULL,
  `idestado_final` INT NULL,
  `idestado_ot` INT NOT NULL,
  `idubicacion_fisica` INT NOT NULL,
  `fecha_programacion` TIMESTAMP NULL,
  `fecha_conformidad` TIMESTAMP NULL,
  `costo_total` FLOAT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `nombre_ejecutor` VARCHAR(200) NULL,
  PRIMARY KEY (`idot_vmetrologica`),
  INDEX `fk_ot_vmetrologicas_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_ot_vmetrologicas_users1_idx` (`id_usuariosolicitante` ASC),
  INDEX `fk_ot_vmetrologicas_activos1_idx` (`idactivo` ASC),
  INDEX `fk_ot_vmetrologicas_estados1_idx` (`idestado_inicial` ASC),
  INDEX `fk_ot_vmetrologicas_estados2_idx` (`idestado_final` ASC),
  INDEX `fk_ot_vmetrologicas_estados3_idx` (`idestado_ot` ASC),
  INDEX `fk_ot_vmetrologicas_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_ot_vmetrologicas_users2_idx` (`id_usuarioelaborador` ASC),
  CONSTRAINT `fk_ot_vmetrologicas_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_vmetrologicas_users1`
    FOREIGN KEY (`id_usuariosolicitante`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_vmetrologicas_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_vmetrologicas_estados1`
    FOREIGN KEY (`idestado_inicial`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_vmetrologicas_estados2`
    FOREIGN KEY (`idestado_final`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_vmetrologicas_estados3`
    FOREIGN KEY (`idestado_ot`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_vmetrologicas_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_vmetrologicas_users2`
    FOREIGN KEY (`id_usuarioelaborador`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`documentos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`documentos` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `autor` VARCHAR(100) NOT NULL,
  `codigo_archivamiento` VARCHAR(100) NOT NULL,
  `ubicacion` VARCHAR(100) NOT NULL,
  `url` VARCHAR(200) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idtipo_documento` INT NOT NULL,
  `idreporte_instalacion` INT NULL,
  `idactivo` INT NULL,
  `idcontrato` INT NULL,
  `idreporte_incumplimiento` INT NULL,
  `idsolicitud_compra` INT NULL,
  `idestado` INT NOT NULL,
  `idtipo_acta` INT NULL,
  `idproveedor` INT NULL,
  `fecha_acta` TIMESTAMP NULL DEFAULT NULL,
  `idreporte_retiro` INT NULL,
  `idot_vmetrologica` INT NULL,
  `nombre_archivo` VARCHAR(200) NULL,
  `nombre_archivo_encriptado` VARCHAR(200) NULL,
  PRIMARY KEY (`iddocumento`),
  INDEX `fk_documentos_tipo_documentos1_idx` (`idtipo_documento` ASC),
  INDEX `fk_documentos_reporte_instalaciones1_idx` (`idreporte_instalacion` ASC),
  INDEX `fk_documentos_activos1_idx` (`idactivo` ASC),
  INDEX `fk_documentos_contratos1_idx` (`idcontrato` ASC),
  INDEX `fk_documentos_reporte_incumplimientos1_idx` (`idreporte_incumplimiento` ASC),
  INDEX `fk_documentos_solicitud_compras1_idx` (`idsolicitud_compra` ASC),
  INDEX `fk_documentos_estados1_idx` (`idestado` ASC),
  INDEX `fk_documentos_tipo_actas1_idx` (`idtipo_acta` ASC),
  INDEX `fk_documentos_proveedores1_idx` (`idproveedor` ASC),
  INDEX `fk_documentos_reporte_retiros1_idx` (`idreporte_retiro` ASC),
  INDEX `fk_documentos_ot_vmetrologicas1_idx` (`idot_vmetrologica` ASC),
  CONSTRAINT `fk_documentos_tipo_documentos1`
    FOREIGN KEY (`idtipo_documento`)
    REFERENCES `gts_db`.`tipo_documentos` (`idtipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_reporte_instalaciones1`
    FOREIGN KEY (`idreporte_instalacion`)
    REFERENCES `gts_db`.`reporte_instalaciones` (`idreporte_instalacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_contratos1`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `gts_db`.`contratos` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_reporte_incumplimientos1`
    FOREIGN KEY (`idreporte_incumplimiento`)
    REFERENCES `gts_db`.`reporte_incumplimientos` (`idreporte_incumplimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_solicitud_compras1`
    FOREIGN KEY (`idsolicitud_compra`)
    REFERENCES `gts_db`.`solicitud_compras` (`idsolicitud_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_tipo_actas1`
    FOREIGN KEY (`idtipo_acta`)
    REFERENCES `gts_db`.`tipo_actas` (`idtipo_acta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `gts_db`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_reporte_retiros1`
    FOREIGN KEY (`idreporte_retiro`)
    REFERENCES `gts_db`.`reporte_retiros` (`idreporte_retiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_ot_vmetrologicas1`
    FOREIGN KEY (`idot_vmetrologica`)
    REFERENCES `gts_db`.`ot_vmetrologicas` (`idot_vmetrologica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gts_db`.`soporte_tecnicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`soporte_tecnicos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`soporte_tecnicos` (
  `idsoporte_tecnico` INT NOT NULL AUTO_INCREMENT,
  `numero_doc_identidad` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellido_pat` VARCHAR(200) NOT NULL,
  `apellido_mat` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `idtipo_documento` INT NOT NULL,
  `idproveedor` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idsoporte_tecnico`),
  INDEX `fk_soporte_tecnicos_tipo_doc_identidades1_idx` (`idtipo_documento` ASC),
  INDEX `fk_soporte_tecnicos_proveedores1_idx` (`idproveedor` ASC),
  CONSTRAINT `fk_soporte_tecnicos_tipo_doc_identidades1`
    FOREIGN KEY (`idtipo_documento`)
    REFERENCES `gts_db`.`tipo_doc_identidades` (`idtipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soporte_tecnicos_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `gts_db`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`soporte_tecnicosxactivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`soporte_tecnicosxactivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`soporte_tecnicosxactivos` (
  `idsoporte_tecnicosxactivo` INT NOT NULL AUTO_INCREMENT,
  `idsoporte_tecnico` INT NOT NULL,
  `idactivo` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idsoporte_tecnicosxactivo`),
  INDEX `fk_soporte_tecnicos_has_activos_activos1_idx` (`idactivo` ASC),
  INDEX `fk_soporte_tecnicos_has_activos_soporte_tecnicos1_idx` (`idsoporte_tecnico` ASC),
  INDEX `fk_soporte_tecnicosxactivos_estados1_idx` (`idestado` ASC),
  CONSTRAINT `fk_soporte_tecnicos_has_activos_soporte_tecnicos1`
    FOREIGN KEY (`idsoporte_tecnico`)
    REFERENCES `gts_db`.`soporte_tecnicos` (`idsoporte_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soporte_tecnicos_has_activos_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soporte_tecnicosxactivos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`componentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`componentes` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`componentes` (
  `idcomponente` INT NOT NULL AUTO_INCREMENT,
  `numero_pieza` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idmodelo_equipo` INT NOT NULL,
  PRIMARY KEY (`idcomponente`),
  INDEX `fk_componentes_modelo_activos1_idx` (`idmodelo_equipo` ASC),
  CONSTRAINT `fk_componentes_modelo_activos1`
    FOREIGN KEY (`idmodelo_equipo`)
    REFERENCES `gts_db`.`modelo_activos` (`idmodelo_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`consumibles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`consumibles` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`consumibles` (
  `idconsumible` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cantidad` INT NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `idmodelo_equipo` INT NOT NULL,
  PRIMARY KEY (`idconsumible`),
  INDEX `fk_consumibles_modelo_activos1_idx` (`idmodelo_equipo` ASC),
  CONSTRAINT `fk_consumibles_modelo_activos1`
    FOREIGN KEY (`idmodelo_equipo`)
    REFERENCES `gts_db`.`modelo_activos` (`idmodelo_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`accesorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`accesorios` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`accesorios` (
  `idaccesorio` INT NOT NULL AUTO_INCREMENT,
  `numero_pieza` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idmodelo_equipo` INT NOT NULL,
  PRIMARY KEY (`idaccesorio`),
  INDEX `fk_accesorios_modelo_activos1_idx` (`idmodelo_equipo` ASC),
  CONSTRAINT `fk_accesorios_modelo_activos1`
    FOREIGN KEY (`idmodelo_equipo`)
    REFERENCES `gts_db`.`modelo_activos` (`idmodelo_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_ot_preventivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_ot_preventivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_ot_preventivos` (
  `idtareas_ot_preventivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idfamilia_activo` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idtareas_ot_preventivo`),
  INDEX `fk_tareas_ot_preventivos_familia_activos1_idx` (`idfamilia_activo` ASC),
  CONSTRAINT `fk_tareas_ot_preventivos_familia_activos1`
    FOREIGN KEY (`idfamilia_activo`)
    REFERENCES `gts_db`.`familia_activos` (`idfamilia_activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`solicitud_orden_trabajos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`solicitud_orden_trabajos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`solicitud_orden_trabajos` (
  `idsolicitud_orden_trabajo` INT NOT NULL AUTO_INCREMENT,
  `sot_tipo_abreviatura` VARCHAR(3) NULL,
  `sot_correlativo` VARCHAR(4) NULL,
  `sot_activo_abreviatura` VARCHAR(2) NULL,
  `fecha_solicitud` TIMESTAMP NOT NULL,
  `especificacion_servicio` VARCHAR(100) NOT NULL,
  `motivo` VARCHAR(200) NOT NULL,
  `justificacion` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `id` INT NOT NULL,
  `idestado` INT NOT NULL,
  `idactivo` INT NOT NULL,
  PRIMARY KEY (`idsolicitud_orden_trabajo`),
  INDEX `fk_solicitud_orden_trabajos_users1_idx` (`id` ASC),
  INDEX `fk_solicitud_orden_trabajos_estados1_idx` (`idestado` ASC),
  INDEX `fk_solicitud_orden_trabajos_activos1_idx` (`idactivo` ASC),
  CONSTRAINT `fk_solicitud_orden_trabajos_users1`
    FOREIGN KEY (`id`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_orden_trabajos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_orden_trabajos_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`detalle_reporte_instalaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`detalle_reporte_instalaciones` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`detalle_reporte_instalaciones` (
  `iddetalle_reporte_instalacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_tarea` VARCHAR(100) NOT NULL,
  `tarea_realizada` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idreporte_instalacion` INT NOT NULL,
  PRIMARY KEY (`iddetalle_reporte_instalacion`),
  INDEX `fk_detalle_reporte_instalaciones_reporte_instalaciones1_idx` (`idreporte_instalacion` ASC),
  CONSTRAINT `fk_detalle_reporte_instalaciones_reporte_instalaciones1`
    FOREIGN KEY (`idreporte_instalacion`)
    REFERENCES `gts_db`.`reporte_instalaciones` (`idreporte_instalacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`cotizaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`cotizaciones` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`cotizaciones` (
  `idcotizacion` INT NOT NULL AUTO_INCREMENT,
  `precio` FLOAT NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idproveedor` INT NOT NULL,
  `idestado` INT NOT NULL,
  `idmodelo_equipo` INT NOT NULL,
  PRIMARY KEY (`idcotizacion`),
  INDEX `fk_cotizaciones_proveedores1_idx` (`idproveedor` ASC),
  INDEX `fk_cotizaciones_estados1_idx` (`idestado` ASC),
  INDEX `fk_cotizaciones_modelo_activos1_idx` (`idmodelo_equipo` ASC),
  CONSTRAINT `fk_cotizaciones_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `gts_db`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotizaciones_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotizaciones_modelo_activos1`
    FOREIGN KEY (`idmodelo_equipo`)
    REFERENCES `gts_db`.`modelo_activos` (`idmodelo_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`prioridades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`prioridades` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`prioridades` (
  `idprioridad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idprioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_fallas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_fallas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_fallas` (
  `idtipo_falla` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_falla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`detalle_solicitud_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`detalle_solicitud_compras` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`detalle_solicitud_compras` (
  `iddetalle_solicitud_compra` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(100) NOT NULL,
  `serie_parte` VARCHAR(100) NOT NULL,
  `cantidad` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idsolicitud_compra` INT NOT NULL,
  PRIMARY KEY (`iddetalle_solicitud_compra`),
  INDEX `fk_detalle_solicitud_compras_solicitud_compras1_idx` (`idsolicitud_compra` ASC),
  CONSTRAINT `fk_detalle_solicitud_compras_solicitud_compras1`
    FOREIGN KEY (`idsolicitud_compra`)
    REFERENCES `gts_db`.`solicitud_compras` (`idsolicitud_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_correctivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_correctivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_correctivos` (
  `idot_correctivo` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(2) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `numero_ficha` INT NULL DEFAULT NULL,
  `ot_activo_abreviatura` VARCHAR(2) NULL,
  `idubicacion_fisica` INT NOT NULL,
  `id_usuariosolicitante` INT NOT NULL,
  `id_usuarioelaborador` INT NOT NULL,
  `idsolicitud_orden_trabajo` INT NOT NULL,
  `idestado_inicial` INT NULL,
  `idestado_final` INT NULL,
  `idestado_ot` INT NOT NULL,
  `idactivo` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `idprioridad` INT NOT NULL,
  `idtipo_falla` INT NOT NULL,
  `fecha_conformidad` TIMESTAMP NULL,
  `fecha_programacion` TIMESTAMP NULL,
  `descripcion_problema` VARCHAR(500) NULL,
  `diagnostico_falla` VARCHAR(500) NULL,
  `nombre_ejecutor` VARCHAR(200) NULL,
  `fecha_inicio_ejecucion` TIMESTAMP NULL,
  `fecha_termino_ejecucion` TIMESTAMP NULL,
  `sin_interrupcion_servicio` INT NULL,
  `costo_total_repuestos` FLOAT NULL,
  `costo_total_personal` FLOAT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idot_correctivo`),
  INDEX `fk_ot_correctivos_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_ot_correctivos_users1_idx` (`id_usuariosolicitante` ASC),
  INDEX `fk_ot_correctivos_users2_idx` (`id_usuarioelaborador` ASC),
  INDEX `fk_ot_correctivos_solicitud_orden_trabajos1_idx` (`idsolicitud_orden_trabajo` ASC),
  INDEX `fk_ot_correctivos_estados1_idx` (`idestado_inicial` ASC),
  INDEX `fk_ot_correctivos_estados2_idx` (`idestado_final` ASC),
  INDEX `fk_ot_correctivos_estados3_idx` (`idestado_ot` ASC),
  INDEX `fk_ot_correctivos_activos1_idx` (`idactivo` ASC),
  INDEX `fk_ot_correctivos_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_ot_correctivos_prioridades1_idx` (`idprioridad` ASC),
  INDEX `fk_ot_correctivos_tipo_fallas1_idx` (`idtipo_falla` ASC),
  CONSTRAINT `fk_ot_correctivos_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_users1`
    FOREIGN KEY (`id_usuariosolicitante`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_users2`
    FOREIGN KEY (`id_usuarioelaborador`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_solicitud_orden_trabajos1`
    FOREIGN KEY (`idsolicitud_orden_trabajo`)
    REFERENCES `gts_db`.`solicitud_orden_trabajos` (`idsolicitud_orden_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_estados1`
    FOREIGN KEY (`idestado_inicial`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_estados2`
    FOREIGN KEY (`idestado_final`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_estados3`
    FOREIGN KEY (`idestado_ot`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_prioridades1`
    FOREIGN KEY (`idprioridad`)
    REFERENCES `gts_db`.`prioridades` (`idprioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_correctivos_tipo_fallas1`
    FOREIGN KEY (`idtipo_falla`)
    REFERENCES `gts_db`.`tipo_fallas` (`idtipo_falla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`repuestos_ot_correctivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`repuestos_ot_correctivo` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`repuestos_ot_correctivo` (
  `idrepuestos_ot_correctivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `codigo` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `costo` FLOAT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `idot_correctivo` INT NOT NULL,
  PRIMARY KEY (`idrepuestos_ot_correctivo`),
  INDEX `fk_repuestos_ot_correctivo_ot_correctivos1_idx` (`idot_correctivo` ASC),
  CONSTRAINT `fk_repuestos_ot_correctivo_ot_correctivos1`
    FOREIGN KEY (`idot_correctivo`)
    REFERENCES `gts_db`.`ot_correctivos` (`idot_correctivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_inspec_infras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_inspec_infras` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_inspec_infras` (
  `idot_inspec_infra` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(3) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `anho_construccion` TIMESTAMP NULL,
  `fecha_inicio` TIMESTAMP NULL,
  `capacidad_instalada` FLOAT NULL,
  `fecha_fin` TIMESTAMP NULL,
  `observacion_inst_electrica` VARCHAR(500) NULL,
  `observacion_infra` VARCHAR(500) NULL,
  `resultado_inst_electrica` VARCHAR(200) NULL,
  `resultado_infra` VARCHAR(200) NULL,
  `imagen_url_ins_electrica` VARCHAR(200) NULL,
  `imagen_url_infra` VARCHAR(200) NULL,
  `idestado` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `idubicacion_fisica` INT NOT NULL,
  `id_ingeniero` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idot_inspec_infra`),
  INDEX `fk_ot_inspec_infras_estados1_idx` (`idestado` ASC),
  INDEX `fk_ot_inspec_infras_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_ot_inspec_infras_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_ot_inspec_infras_users1_idx` (`id_ingeniero` ASC),
  CONSTRAINT `fk_ot_inspec_infras_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_infras_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_infras_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_infras_users1`
    FOREIGN KEY (`id_ingeniero`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_preventivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_preventivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_preventivos` (
  `idot_preventivo` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(2) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `ot_activo_abreviatura` VARCHAR(2) NULL,
  `numero_ficha` INT NULL,
  `id_usuariosolicitante` INT NOT NULL,
  `id_usuarioelaborador` INT NOT NULL,
  `idubicacion_fisica` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `idactivo` INT NOT NULL,
  `idestado_inicial` INT NULL,
  `idestado_final` INT NULL,
  `idestado_ot` INT NOT NULL,
  `fecha_conformidad` TIMESTAMP NULL,
  `fecha_programacion` TIMESTAMP NULL,
  `costo_total_repuestos` FLOAT NULL,
  `costo_total_personal` FLOAT NULL,
  `fecha_inicio_ejecucion` TIMESTAMP NULL,
  `fecha_termino_ejecucion` TIMESTAMP NULL,
  `sin_interrupcion_servicio` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `nombre_ejecutor` VARCHAR(200) NULL,
  PRIMARY KEY (`idot_preventivo`),
  INDEX `fk_ot_preventivos_users1_idx` (`id_usuariosolicitante` ASC),
  INDEX `fk_ot_preventivos_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_ot_preventivos_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_ot_preventivos_activos1_idx` (`idactivo` ASC),
  INDEX `fk_ot_preventivos_estados1_idx` (`idestado_inicial` ASC),
  INDEX `fk_ot_preventivos_estados2_idx` (`idestado_final` ASC),
  INDEX `fk_ot_preventivos_estados3_idx` (`idestado_ot` ASC),
  INDEX `fk_ot_preventivos_users2_idx` (`id_usuarioelaborador` ASC),
  CONSTRAINT `fk_ot_preventivos_users1`
    FOREIGN KEY (`id_usuariosolicitante`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_preventivos_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_preventivos_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_preventivos_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_preventivos_estados1`
    FOREIGN KEY (`idestado_inicial`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_preventivos_estados2`
    FOREIGN KEY (`idestado_final`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_preventivos_estados3`
    FOREIGN KEY (`idestado_ot`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_preventivos_users2`
    FOREIGN KEY (`id_usuarioelaborador`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_inspec_hospitalarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_inspec_hospitalarios` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_inspec_hospitalarios` (
  `idot_inspec_hospitalario` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(3) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `capacidad_instalada` FLOAT NULL,
  `anho_construccion` TIMESTAMP NULL,
  `fecha_inicio` TIMESTAMP NULL,
  `fecha_fin` TIMESTAMP NULL,
  `idubicacion_fisica` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `id_ingeniero` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idestado_ot` INT NOT NULL,
  PRIMARY KEY (`idot_inspec_hospitalario`),
  INDEX `fk_ot_inspec_hospitalarios_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_ot_inspec_hospitalarios_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_ot_inspec_hospitalarios_users1_idx` (`id_ingeniero` ASC),
  INDEX `fk_ot_inspec_hospitalarios_estados1_idx` (`idestado_ot` ASC),
  CONSTRAINT `fk_ot_inspec_hospitalarios_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_hospitalarios_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_hospitalarios_users1`
    FOREIGN KEY (`id_ingeniero`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_hospitalarios_estados1`
    FOREIGN KEY (`idestado_ot`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_retiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_retiros` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_retiros` (
  `idot_retiro` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(2) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `ot_activo_abreviatura` VARCHAR(2) NULL,
  `id_usuariosolicitante` INT NOT NULL,
  `id_usuarioelaborador` INT NOT NULL,
  `fecha_conformidad` TIMESTAMP NULL,
  `fecha_programacion` TIMESTAMP NULL,
  `nombre_ejecutor` VARCHAR(100) NULL,
  `costo_total_personal` FLOAT NULL,
  `idubicacion_fisica` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `idactivo` INT NOT NULL,
  `idestado_inicial` INT NULL,
  `idestado_final` INT NULL,
  `idestado_ot` INT NOT NULL,
  `idreporte_retiro` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idot_retiro`),
  INDEX `fk_orden_trabajo_retiro_servicios_users1_idx` (`id_usuariosolicitante` ASC),
  INDEX `fk_orden_trabajo_retiro_servicios_users2_idx` (`id_usuarioelaborador` ASC),
  INDEX `fk_ot_retiros_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_ot_retiros_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_ot_retiros_activos1_idx` (`idactivo` ASC),
  INDEX `fk_ot_retiros_estados1_idx` (`idestado_inicial` ASC),
  INDEX `fk_ot_retiros_estados2_idx` (`idestado_final` ASC),
  INDEX `fk_ot_retiros_estados3_idx` (`idestado_ot` ASC),
  INDEX `fk_ot_retiros_reporte_retiros1_idx` (`idreporte_retiro` ASC),
  CONSTRAINT `fk_orden_trabajo_retiro_servicios_users1`
    FOREIGN KEY (`id_usuariosolicitante`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_trabajo_retiro_servicios_users2`
    FOREIGN KEY (`id_usuarioelaborador`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_retiros_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_retiros_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_retiros_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_retiros_estados1`
    FOREIGN KEY (`idestado_inicial`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_retiros_estados2`
    FOREIGN KEY (`idestado_final`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_retiros_estados3`
    FOREIGN KEY (`idestado_ot`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_retiros_reporte_retiros1`
    FOREIGN KEY (`idreporte_retiro`)
    REFERENCES `gts_db`.`reporte_retiros` (`idreporte_retiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_busqueda_infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_busqueda_infos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_busqueda_infos` (
  `idtipo_busqueda_info` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_busqueda_info`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`solicitud_busqueda_infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`solicitud_busqueda_infos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`solicitud_busqueda_infos` (
  `idsolicitud_busqueda_info` INT NOT NULL AUTO_INCREMENT,
  `sot_tipo_abreviatura` VARCHAR(3) NULL,
  `sot_correlativo` VARCHAR(4) NULL,
  `fecha_solicitud` TIMESTAMP NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `motivo` VARCHAR(200) NOT NULL,
  `detalle` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `id` INT NOT NULL,
  `id_usuarioencargado` INT NOT NULL,
  `idestado` INT NOT NULL,
  `idarea` INT NOT NULL,
  `idtipo_busqueda_info` INT NOT NULL,
  PRIMARY KEY (`idsolicitud_busqueda_info`),
  INDEX `fk_solicitud_busqueda_infos_areas1_idx` (`idarea` ASC),
  INDEX `fk_solicitud_busqueda_infos_tipo_busqueda_infos1_idx` (`idtipo_busqueda_info` ASC),
  INDEX `fk_solicitud_busqueda_infos_users1_idx` (`id_usuarioencargado` ASC),
  CONSTRAINT `fk_solicitud_busqueda_infos_areas1`
    FOREIGN KEY (`idarea`)
    REFERENCES `gts_db`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_busqueda_infos_tipo_busqueda_infos1`
    FOREIGN KEY (`idtipo_busqueda_info`)
    REFERENCES `gts_db`.`tipo_busqueda_infos` (`idtipo_busqueda_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_busqueda_infos_users1`
    FOREIGN KEY (`id_usuarioencargado`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_busqueda_infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_busqueda_infos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_busqueda_infos` (
  `idot_busqueda_info` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(3) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `idarea` INT NOT NULL,
  `id_usuariosolicitante` INT NOT NULL,
  `id_usuarioelaborador` INT NOT NULL,
  `id_usuarioencargado` INT NOT NULL,
  `fecha_conformidad` TIMESTAMP NULL,
  `fecha_programacion` TIMESTAMP NULL,
  `costo_total_personal` FLOAT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idestado_ot` INT NOT NULL,
  `idsolicitud_busqueda_info` INT NOT NULL,
  PRIMARY KEY (`idot_busqueda_info`),
  INDEX `fk_ot_busqueda_infos_users1_idx` (`id_usuariosolicitante` ASC),
  INDEX `fk_ot_busqueda_infos_users2_idx` (`id_usuarioelaborador` ASC),
  INDEX `fk_ot_busqueda_infos_areas1_idx` (`idarea` ASC),
  INDEX `fk_ot_busqueda_infos_estados1_idx` (`idestado_ot` ASC),
  INDEX `fk_ot_busqueda_infos_solicitud_busqueda_infos1_idx` (`idsolicitud_busqueda_info` ASC),
  INDEX `fk_ot_busqueda_infos_users3_idx` (`id_usuarioencargado` ASC),
  CONSTRAINT `fk_ot_busqueda_infos_users1`
    FOREIGN KEY (`id_usuariosolicitante`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_busqueda_infos_users2`
    FOREIGN KEY (`id_usuarioelaborador`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_busqueda_infos_areas1`
    FOREIGN KEY (`idarea`)
    REFERENCES `gts_db`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_busqueda_infos_estados1`
    FOREIGN KEY (`idestado_ot`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_busqueda_infos_solicitud_busqueda_infos1`
    FOREIGN KEY (`idsolicitud_busqueda_info`)
    REFERENCES `gts_db`.`solicitud_busqueda_infos` (`idsolicitud_busqueda_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_busqueda_infos_users3`
    FOREIGN KEY (`id_usuarioencargado`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_inspec_equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_inspec_equipos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_inspec_equipos` (
  `idot_inspec_equipo` INT NOT NULL AUTO_INCREMENT,
  `ot_tipo_abreviatura` VARCHAR(3) NULL,
  `ot_correlativo` VARCHAR(4) NULL,
  `numero_ficha` INT NULL,
  `fecha_inicio` TIMESTAMP NULL,
  `fecha_fin` TIMESTAMP NULL,
  `idestado` INT NOT NULL,
  `idubicacion_fisica` INT NULL,
  `idservicio` INT NOT NULL,
  `id_ingeniero` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idot_inspec_equipo`),
  INDEX `fk_ot_inspec_equipos_estados1_idx` (`idestado` ASC),
  INDEX `fk_ot_inspec_equipos_ubicacion_fisicas1_idx` (`idubicacion_fisica` ASC),
  INDEX `fk_ot_inspec_equipos_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_ot_inspec_equipos_users1_idx` (`id_ingeniero` ASC),
  CONSTRAINT `fk_ot_inspec_equipos_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_equipos_ubicacion_fisicas1`
    FOREIGN KEY (`idubicacion_fisica`)
    REFERENCES `gts_db`.`ubicacion_fisicas` (`idubicacion_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_equipos_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_equipos_users1`
    FOREIGN KEY (`id_ingeniero`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_inspec_infras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_inspec_infras` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_inspec_infras` (
  `idtareas_inspec_infra` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtareas_inspec_infra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_inspec_inst_electricas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_inspec_inst_electricas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_inspec_inst_electricas` (
  `idtareas_inspec_inst_electrica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtareas_inspec_inst_electrica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`personal_ot_vmetrologicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`personal_ot_vmetrologicas` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`personal_ot_vmetrologicas` (
  `idpersonal_ot_vmetrologica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `horas_hombre` FLOAT NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_vmetrologica` INT NOT NULL,
  PRIMARY KEY (`idpersonal_ot_vmetrologica`),
  INDEX `fk_personal_ot_vmetrologicas_ot_vmetrologicas1_idx` (`idot_vmetrologica` ASC),
  CONSTRAINT `fk_personal_ot_vmetrologicas_ot_vmetrologicas1`
    FOREIGN KEY (`idot_vmetrologica`)
    REFERENCES `gts_db`.`ot_vmetrologicas` (`idot_vmetrologica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_ot_correctivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_ot_correctivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_ot_correctivos` (
  `idtareas_ot_correctivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_correctivo` INT NOT NULL,
  `idestado_realizado` INT NOT NULL,
  PRIMARY KEY (`idtareas_ot_correctivo`),
  INDEX `fk_tareas_ot_correctivos_ot_correctivos1_idx` (`idot_correctivo` ASC),
  INDEX `fk_tareas_ot_correctivos_estados1_idx` (`idestado_realizado` ASC),
  CONSTRAINT `fk_tareas_ot_correctivos_ot_correctivos1`
    FOREIGN KEY (`idot_correctivo`)
    REFERENCES `gts_db`.`ot_correctivos` (`idot_correctivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_ot_correctivos_estados1`
    FOREIGN KEY (`idestado_realizado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`personal_ot_correctivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`personal_ot_correctivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`personal_ot_correctivos` (
  `idpersonal_ot_correctivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `horas_hombre` FLOAT NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_correctivo` INT NOT NULL,
  PRIMARY KEY (`idpersonal_ot_correctivo`),
  INDEX `fk_personal_ot_correctivos_ot_correctivos1_idx` (`idot_correctivo` ASC),
  CONSTRAINT `fk_personal_ot_correctivos_ot_correctivos1`
    FOREIGN KEY (`idot_correctivo`)
    REFERENCES `gts_db`.`ot_correctivos` (`idot_correctivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`personal_ot_preventivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`personal_ot_preventivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`personal_ot_preventivos` (
  `idpersonal_ot_preventivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `horas_hombre` FLOAT NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_preventivo` INT NOT NULL,
  PRIMARY KEY (`idpersonal_ot_preventivo`),
  INDEX `fk_personal_ot_preventivos_ot_preventivos1_idx` (`idot_preventivo` ASC),
  CONSTRAINT `fk_personal_ot_preventivos_ot_preventivos1`
    FOREIGN KEY (`idot_preventivo`)
    REFERENCES `gts_db`.`ot_preventivos` (`idot_preventivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`repuestos_ot_preventivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`repuestos_ot_preventivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`repuestos_ot_preventivos` (
  `idrepuestos_ot_preventivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `codigo` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `costo` FLOAT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_preventivo` INT NOT NULL,
  PRIMARY KEY (`idrepuestos_ot_preventivo`),
  INDEX `fk_repuestos_ot_preventivos_ot_preventivos1_idx` (`idot_preventivo` ASC),
  CONSTRAINT `fk_repuestos_ot_preventivos_ot_preventivos1`
    FOREIGN KEY (`idot_preventivo`)
    REFERENCES `gts_db`.`ot_preventivos` (`idot_preventivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_inspec_equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_inspec_equipos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_inspec_equipos` (
  `idtareas_inspec_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idfamilia_activo` INT NOT NULL,
  PRIMARY KEY (`idtareas_inspec_equipo`),
  INDEX `fk_tareas_inspec_equipos_familia_activos1_idx` (`idfamilia_activo` ASC),
  CONSTRAINT `fk_tareas_inspec_equipos_familia_activos1`
    FOREIGN KEY (`idfamilia_activo`)
    REFERENCES `gts_db`.`familia_activos` (`idfamilia_activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_inspec_hospitalarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_inspec_hospitalarios` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_inspec_hospitalarios` (
  `idtareas_inspec_hospitalario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_inspec_hospitalario` INT NOT NULL,
  `idestado_realizado` INT NOT NULL,
  PRIMARY KEY (`idtareas_inspec_hospitalario`),
  INDEX `fk_tareas_inspec_hospitalarios_ot_inspec_hospitalarios1_idx` (`idot_inspec_hospitalario` ASC),
  INDEX `fk_tareas_inspec_hospitalarios_estados1_idx` (`idestado_realizado` ASC),
  CONSTRAINT `fk_tareas_inspe_hospitalarios_ot_inspec_hospitalarios1`
    FOREIGN KEY (`idot_inspec_hospitalario`)
    REFERENCES `gts_db`.`ot_inspec_hospitalarios` (`idot_inspec_hospitalario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_inspe_hospitalarios_estados1`
    FOREIGN KEY (`idestado_realizado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_ot_retiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_ot_retiros` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_ot_retiros` (
  `idtareas_ot_retiro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_retiro` INT NOT NULL,
  `idestado_realizado` INT NOT NULL,
  PRIMARY KEY (`idtareas_ot_retiro`),
  INDEX `fk_tareas_ot_retiros_ot_retiros1_idx` (`idot_retiro` ASC),
  INDEX `fk_tareas_ot_retiros_estados1_idx` (`idestado_realizado` ASC),
  CONSTRAINT `fk_tareas_ot_retiros_ot_retiros1`
    FOREIGN KEY (`idot_retiro`)
    REFERENCES `gts_db`.`ot_retiros` (`idot_retiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_ot_retiros_estados1`
    FOREIGN KEY (`idestado_realizado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`personal_ot_retiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`personal_ot_retiros` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`personal_ot_retiros` (
  `idpersonal_ot_retiro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `horas_hombre` FLOAT NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_retiro` INT NOT NULL,
  PRIMARY KEY (`idpersonal_ot_retiro`),
  INDEX `fk_personal_ot_retiros_ot_retiros1_idx` (`idot_retiro` ASC),
  CONSTRAINT `fk_personal_ot_retiros_ot_retiros1`
    FOREIGN KEY (`idot_retiro`)
    REFERENCES `gts_db`.`ot_retiros` (`idot_retiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_ot_busqueda_infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_ot_busqueda_infos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_ot_busqueda_infos` (
  `idtareas_ot_busqueda_info` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_busqueda_info` INT NOT NULL,
  `idestado_realizado` INT NOT NULL,
  PRIMARY KEY (`idtareas_ot_busqueda_info`),
  INDEX `fk_tareas_ot_busqueda_infos_ot_busqueda_infos1_idx` (`idot_busqueda_info` ASC),
  INDEX `fk_tareas_ot_busqueda_infos_estados1_idx` (`idestado_realizado` ASC),
  CONSTRAINT `fk_tareas_ot_busqueda_infos_ot_busqueda_infos1`
    FOREIGN KEY (`idot_busqueda_info`)
    REFERENCES `gts_db`.`ot_busqueda_infos` (`idot_busqueda_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_ot_busqueda_infos_estados1`
    FOREIGN KEY (`idestado_realizado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`personal_ot_busqueda_infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`personal_ot_busqueda_infos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`personal_ot_busqueda_infos` (
  `idpersonal_ot_busqueda_info` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `horas_hombre` FLOAT NOT NULL,
  `costo` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idot_busqueda_info` INT NOT NULL,
  PRIMARY KEY (`idpersonal_ot_busqueda_info`),
  INDEX `fk_personal_ot_busqueda_infos_ot_busqueda_infos1_idx` (`idot_busqueda_info` ASC),
  CONSTRAINT `fk_personal_ot_busqueda_infos_ot_busqueda_infos1`
    FOREIGN KEY (`idot_busqueda_info`)
    REFERENCES `gts_db`.`ot_busqueda_infos` (`idot_busqueda_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_ot_preventivosxot_preventivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_ot_preventivosxot_preventivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_ot_preventivosxot_preventivos` (
  `idtareas_ot_preventivosxot_preventivo` INT NOT NULL AUTO_INCREMENT,
  `idtareas_ot_preventivo` INT NOT NULL,
  `idot_preventivo` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idestado_realizado` INT NOT NULL,
  INDEX `fk_tareas_ot_preventivos_has_ot_preventivos_ot_preventivos1_idx` (`idot_preventivo` ASC),
  INDEX `fk_tareas_ot_preventivos_has_ot_preventivos_tareas_ot_preve_idx` (`idtareas_ot_preventivo` ASC),
  PRIMARY KEY (`idtareas_ot_preventivosxot_preventivo`),
  INDEX `fk_tareas_ot_preventivosxot_preventivos_estados1_idx` (`idestado_realizado` ASC),
  CONSTRAINT `fk_tareas_ot_preventivos_has_ot_preventivos_tareas_ot_prevent1`
    FOREIGN KEY (`idtareas_ot_preventivo`)
    REFERENCES `gts_db`.`tareas_ot_preventivos` (`idtareas_ot_preventivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_ot_preventivos_has_ot_preventivos_ot_preventivos1`
    FOREIGN KEY (`idot_preventivo`)
    REFERENCES `gts_db`.`ot_preventivos` (`idot_preventivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_ot_preventivosxot_preventivos_estados1`
    FOREIGN KEY (`idestado_realizado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_inspec_equiposxactivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_inspec_equiposxactivos` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_inspec_equiposxactivos` (
  `idot_inspec_equiposxactivo` INT NOT NULL AUTO_INCREMENT,
  `idot_inspec_equipo` INT NOT NULL,
  `idactivo` INT NOT NULL,
  `observaciones` VARCHAR(200) NULL,
  `imagen_url` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `nombre_archivo` VARCHAR(200) NULL,
  `nombre_archivo_encriptado` VARCHAR(200) NULL,
  INDEX `fk_ot_inspec_equipos_has_activos_activos1_idx` (`idactivo` ASC),
  INDEX `fk_ot_inspec_equipos_has_activos_ot_inspec_equipos1_idx` (`idot_inspec_equipo` ASC),
  PRIMARY KEY (`idot_inspec_equiposxactivo`),
  CONSTRAINT `fk_ot_inspec_equipos_has_activos_ot_inspec_equipos1`
    FOREIGN KEY (`idot_inspec_equipo`)
    REFERENCES `gts_db`.`ot_inspec_equipos` (`idot_inspec_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_equipos_has_activos_activos1`
    FOREIGN KEY (`idactivo`)
    REFERENCES `gts_db`.`activos` (`idactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`ot_inspec_equiposxactivosxtareas_inspec_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`ot_inspec_equiposxactivosxtareas_inspec_equipo` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`ot_inspec_equiposxactivosxtareas_inspec_equipo` (
  `idot_inspec_equiposxactivosxtareas_inspec_equipo` INT NOT NULL AUTO_INCREMENT,
  `idot_inspec_equiposxactivo` INT NOT NULL,
  `idtareas_inspec_equipo` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `idestado_realizado` INT NOT NULL,
  INDEX `fk_ot_inspec_equiposxactivos_has_tareas_inspec_equipos_tare_idx` (`idtareas_inspec_equipo` ASC),
  INDEX `fk_ot_inspec_equiposxactivos_has_tareas_inspec_equipos_ot_i_idx` (`idot_inspec_equiposxactivo` ASC),
  PRIMARY KEY (`idot_inspec_equiposxactivosxtareas_inspec_equipo`),
  INDEX `fk_ot_inspec_equiposxactivosxtareas_inspec_equipo_estados1_idx` (`idestado_realizado` ASC),
  CONSTRAINT `fk_ot_inspec_equiposxactivos_has_tareas_inspec_equipos_ot_ins1`
    FOREIGN KEY (`idot_inspec_equiposxactivo`)
    REFERENCES `gts_db`.`ot_inspec_equiposxactivos` (`idot_inspec_equiposxactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_equiposxactivos_has_tareas_inspec_equipos_tareas1`
    FOREIGN KEY (`idtareas_inspec_equipo`)
    REFERENCES `gts_db`.`tareas_inspec_equipos` (`idtareas_inspec_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ot_inspec_equiposxactivosxtareas_inspec_equipo_estados1`
    FOREIGN KEY (`idestado_realizado`)
    REFERENCES `gts_db`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_inspec_inst_electricasxot_inspec_infras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_inspec_inst_electricasxot_inspec_infras` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_inspec_inst_electricasxot_inspec_infras` (
  `idtareas_inspec_inst_electricasxot_inspec_infra` INT NOT NULL AUTO_INCREMENT,
  `idtareas_inspec_inst_electrica` INT NOT NULL,
  `idot_inspec_infra` INT NOT NULL,
  `idaplica` INT(1) NULL,
  `idcumple` INT(1) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `fk_tareas_inspec_inst_electricas_has_ot_inspec_infras_ot_in_idx` (`idot_inspec_infra` ASC),
  INDEX `fk_tareas_inspec_inst_electricas_has_ot_inspec_infras_tarea_idx` (`idtareas_inspec_inst_electrica` ASC),
  PRIMARY KEY (`idtareas_inspec_inst_electricasxot_inspec_infra`),
  CONSTRAINT `fk_tareas_inspec_inst_electricas_has_ot_inspec_infras_tareas_1`
    FOREIGN KEY (`idtareas_inspec_inst_electrica`)
    REFERENCES `gts_db`.`tareas_inspec_inst_electricas` (`idtareas_inspec_inst_electrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_inspec_inst_electricas_has_ot_inspec_infras_ot_insp1`
    FOREIGN KEY (`idot_inspec_infra`)
    REFERENCES `gts_db`.`ot_inspec_infras` (`idot_inspec_infra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tareas_inspec_infras_has_ot_inspec_infras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tareas_inspec_infras_has_ot_inspec_infras` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tareas_inspec_infras_has_ot_inspec_infras` (
  `idtareas_inspec_infras_has_ot_inspec_infra` INT NOT NULL AUTO_INCREMENT,
  `idtareas_inspec_infra` INT NOT NULL,
  `idot_inspec_infra` INT NOT NULL,
  `iddanho` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `fk_tareas_inspec_infras_has_ot_inspec_infras_ot_inspec_infr_idx` (`idot_inspec_infra` ASC),
  INDEX `fk_tareas_inspec_infras_has_ot_inspec_infras_tareas_inspec__idx` (`idtareas_inspec_infra` ASC),
  PRIMARY KEY (`idtareas_inspec_infras_has_ot_inspec_infra`),
  CONSTRAINT `fk_tareas_inspec_infras_has_ot_inspec_infras_tareas_inspec_in1`
    FOREIGN KEY (`idtareas_inspec_infra`)
    REFERENCES `gts_db`.`tareas_inspec_infras` (`idtareas_inspec_infra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_inspec_infras_has_ot_inspec_infras_ot_inspec_infras1`
    FOREIGN KEY (`idot_inspec_infra`)
    REFERENCES `gts_db`.`ot_inspec_infras` (`idot_inspec_infra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_reporte_CN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_reporte_CN` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_reporte_CN` (
  `idtipo_reporte_CN` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_reporte_CN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`reporte_CN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`reporte_CN` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`reporte_CN` (
  `idreporte_CN` INT NOT NULL AUTO_INCREMENT,
  `numero_reporte_abreviatura` VARCHAR(2) NOT NULL,
  `numero_reporte_correlativo` VARCHAR(4) NOT NULL,
  `numero_reporte_anho` VARCHAR(2) NOT NULL,
  `url` VARCHAR(200) NULL,
  `nombre_archivo` VARCHAR(200) NULL,
  `nombre_archivo_encriptado` VARCHAR(200) NULL,
  `idtipo_reporte_CN` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idot_retiro` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `idarea` INT NOT NULL,
  PRIMARY KEY (`idreporte_CN`),
  INDEX `fk_reporte_CN_tipo_reporte_CN1_idx` (`idtipo_reporte_CN` ASC),
  INDEX `fk_reporte_CN_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_reporte_CN_users1_idx` (`iduser` ASC),
  INDEX `fk_reporte_CN_ot_retiros1_idx` (`idot_retiro` ASC),
  INDEX `fk_reporte_CN_areas1_idx` (`idarea` ASC),
  CONSTRAINT `fk_reporte_CN_tipo_reporte_CN1`
    FOREIGN KEY (`idtipo_reporte_CN`)
    REFERENCES `gts_db`.`tipo_reporte_CN` (`idtipo_reporte_CN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_CN_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_CN_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_CN_ot_retiros1`
    FOREIGN KEY (`idot_retiro`)
    REFERENCES `gts_db`.`ot_retiros` (`idot_retiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_CN_areas1`
    FOREIGN KEY (`idarea`)
    REFERENCES `gts_db`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_reporte_ETES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_reporte_ETES` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_reporte_ETES` (
  `idtipo_reporte_ETES` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_reporte_ETES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`reporte_ETES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`reporte_ETES` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`reporte_ETES` (
  `idreporte_ETES` INT NOT NULL AUTO_INCREMENT,
  `numero_reporte_abreviatura` VARCHAR(2) NOT NULL,
  `numero_reporte_correlativo` VARCHAR(4) NOT NULL,
  `numero_reporte_anho` VARCHAR(2) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `url` VARCHAR(200) NULL,
  `nombre_archivo` VARCHAR(200) NULL,
  `nombre_archivo_encriptado` VARCHAR(200) NULL,
  `iduser` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `idtipo_reporte_ETES` INT NOT NULL,
  PRIMARY KEY (`idreporte_ETES`),
  INDEX `fk_reporte_ETES_users1_idx` (`iduser` ASC),
  INDEX `fk_reporte_ETES_tipo_reporte_ETES1_idx` (`idtipo_reporte_ETES` ASC),
  CONSTRAINT `fk_reporte_ETES_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_ETES_tipo_reporte_ETES1`
    FOREIGN KEY (`idtipo_reporte_ETES`)
    REFERENCES `gts_db`.`tipo_reporte_ETES` (`idtipo_reporte_ETES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`tipo_reporte_PAAC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`tipo_reporte_PAAC` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`tipo_reporte_PAAC` (
  `idtipo_reporte_PAAC` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_reporte_PAAC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gts_db`.`reporte_PAAC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gts_db`.`reporte_PAAC` ;

CREATE TABLE IF NOT EXISTS `gts_db`.`reporte_PAAC` (
  `idreporte_PAAC` INT NOT NULL AUTO_INCREMENT,
  `numero_reporte_abreviatura` VARCHAR(2) NOT NULL,
  `numero_reporte_correlativo` VARCHAR(4) NOT NULL,
  `numero_reporte_anho` VARCHAR(2) NOT NULL,
  `url` VARCHAR(200) NULL,
  `nombre_archivo` VARCHAR(200) NULL,
  `nombre_archivo_encriptado` VARCHAR(200) NULL,
  `idtipo_reporte_PAAC` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  `idarea` INT NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idreporte_PAAC`),
  INDEX `fk_reporte_PAAC_tipo_reporte_PAAC1_idx` (`idtipo_reporte_PAAC` ASC),
  INDEX `fk_reporte_PAAC_servicios1_idx` (`idservicio` ASC),
  INDEX `fk_reporte_PAAC_areas1_idx` (`idarea` ASC),
  INDEX `fk_reporte_PAAC_users1_idx` (`iduser` ASC),
  CONSTRAINT `fk_reporte_PAAC_tipo_reporte_PAAC1`
    FOREIGN KEY (`idtipo_reporte_PAAC`)
    REFERENCES `gts_db`.`tipo_reporte_PAAC` (`idtipo_reporte_PAAC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_PAAC_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `gts_db`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_PAAC_areas1`
    FOREIGN KEY (`idarea`)
    REFERENCES `gts_db`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_PAAC_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `gts_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
