UPDATE entorno_asistencial SET nombre = 'Atención primaria' WHERE id = 1;
UPDATE entorno_asistencial SET nombre = 'Centro de atención comunitaria' WHERE id = 2;
UPDATE entorno_asistencial SET nombre = 'Servicio de salud mental' WHERE id = 3;
UPDATE entorno_asistencial SET nombre = 'Servicio de discapacidad' WHERE id = 4;
UPDATE entorno_asistencial SET nombre = 'Centro de enfermería' WHERE id = 5;
UPDATE entorno_asistencial SET nombre = 'Farmacia comunitaria' WHERE id = 6;
UPDATE entorno_asistencial SET nombre = 'Atención domiciliaria' WHERE id = 7;
UPDATE entorno_asistencial SET nombre = 'Servicios de transporte (incluidas las ambulancias)' WHERE id = 8;
UPDATE entorno_asistencial SET nombre = 'Atención odontológica' WHERE id = 9;
UPDATE entorno_asistencial SET nombre = 'Anatomia patologica' WHERE id = 10;
UPDATE entorno_asistencial SET nombre = 'Atencion inmediata y emergencia' WHERE id = 11;
UPDATE entorno_asistencial SET nombre = 'Banco de leche' WHERE id = 12;
UPDATE entorno_asistencial SET nombre = 'Banco de sangre' WHERE id = 13;
UPDATE entorno_asistencial SET nombre = 'Central de esterilizacion' WHERE id = 14;
UPDATE entorno_asistencial SET nombre = 'Centro obstetrico' WHERE id = 15;
UPDATE entorno_asistencial SET nombre = 'Centro quirurgico' WHERE id = 16;
UPDATE entorno_asistencial SET nombre = 'Cirugia neonatal' WHERE id = 17;
UPDATE entorno_asistencial SET nombre = 'Clinica' WHERE id = 18;
UPDATE entorno_asistencial SET nombre = 'Consulta externa de gineco obstetricia' WHERE id = 19;
UPDATE entorno_asistencial SET nombre = 'Consultorio externo' WHERE id = 20;
UPDATE entorno_asistencial SET nombre = 'Cuidados intensivos neonatal' WHERE id = 21;
UPDATE entorno_asistencial SET nombre = 'Diagnostico por imágenes' WHERE id = 22;
UPDATE entorno_asistencial SET nombre = 'Emergencia' WHERE id = 23;
UPDATE entorno_asistencial SET nombre = 'Especialidades medicas' WHERE id = 24;
UPDATE entorno_asistencial SET nombre = 'Farmacia' WHERE id = 25;
UPDATE entorno_asistencial SET nombre = 'Genetica' WHERE id = 26;
UPDATE entorno_asistencial SET nombre = 'Ginecologia especializada' WHERE id = 27;
UPDATE entorno_asistencial SET nombre = 'Ginecologia oncologica' WHERE id = 28;
UPDATE entorno_asistencial SET nombre = 'Ginecologia patologica' WHERE id = 29;
UPDATE entorno_asistencial SET nombre = 'Intermedios a' WHERE id = 30;
UPDATE entorno_asistencial SET nombre = 'Intermedios b' WHERE id = 31;
UPDATE entorno_asistencial SET nombre = 'Madres delicadas' WHERE id = 32;
UPDATE entorno_asistencial SET nombre = 'Mantenimiento' WHERE id = 33;
UPDATE entorno_asistencial SET nombre = 'Medicina reproductiva' WHERE id = 34;
UPDATE entorno_asistencial SET nombre = 'Nutricion' WHERE id = 35;
UPDATE entorno_asistencial SET nombre = 'Obstetricia a' WHERE id = 36;
UPDATE entorno_asistencial SET nombre = 'Obstetricia b' WHERE id = 37;
UPDATE entorno_asistencial SET nombre = 'Obstetricia c' WHERE id = 38;
UPDATE entorno_asistencial SET nombre = 'Obstetricia d' WHERE id = 39;
UPDATE entorno_asistencial SET nombre = 'Obstetricia e' WHERE id = 40;
UPDATE entorno_asistencial SET nombre = 'Odontoestomatologia' WHERE id = 41;
UPDATE entorno_asistencial SET nombre = 'Patologia clinica' WHERE id = 42;
UPDATE entorno_asistencial SET nombre = 'Psicologia' WHERE id = 43;
UPDATE entorno_asistencial SET nombre = 'Puericultura neonatal' WHERE id = 44;
UPDATE entorno_asistencial SET nombre = 'Recuperacion post anestesica' WHERE id = 45;
UPDATE entorno_asistencial SET nombre = 'Rehabilitacion' WHERE id = 46;
UPDATE entorno_asistencial SET nombre = 'Uci materno' WHERE id = 47;
UPDATE entorno_asistencial SET nombre = 'Unidad medicina fetal' WHERE id = 48;
UPDATE entorno_asistencial SET nombre = 'Otro' WHERE id = 49;